#include <stdint.h>
#include "corkscrew_path.h"
#include "trig.h"

#define TO_FIXED(x) ((int32_t)(x) << 16)

static int32_t iabs(int32_t v) { return v < 0 ? -v : v; }

/* GHZ Scene1.bin's CorkscrewPath entities (Mania filter), both period=384/
 * amplitude=36/angle=0 (verified against assets/ghz/corkscrewpaths.bin's own
 * decoded bytes). angle is NOT read below: CorkscrewPath_Create/_Update
 * never reference self->angle anywhere in the whole source file (only
 * CorkscrewPath_Serialize registers it, for the editor's own property
 * panel) -- provably dead data, same "registered but never read" shape
 * sh_src/spring.c's own SpringDef comment documents for onGround on
 * vertical/diagonal spring rows. */
typedef struct {
	int16_t x, y;
	int16_t period, amplitude, angle;
} CorkscrewPathDef;

/* Direct struct-cast over the linked blob (contrast sh_src/invisible_block.c/
 * spin_booster.c, which cannot do this safely for their own tables -- see
 * each file's own comment on why): this row is 10 bytes, entirely int16
 * fields (2-byte alignment requirement only), and the table's own base is
 * guaranteed 2-byte aligned (tools/gen_assets.py's manifest, align=2) -- so
 * every row's own offset (a multiple of 10, itself a multiple of 2) stays
 * 2-aligned from a 2-aligned base. No 4-byte field exists here the way
 * SpinBoosterRow's boostPower does, so this table has none of either other
 * file's alignment hazards. Same "read the generated bytes directly, at
 * their own linked address" convention sh_src/spring.c's own top comment
 * documents adopting. */
extern const uint16_t ghz_corkscrewpaths_sh[];
static const CorkscrewPathDef *const k_paths =
	(const CorkscrewPathDef *)((const uint8_t *)ghz_corkscrewpaths_sh + 2);
#define CORKSCREWPATH_COUNT (ghz_corkscrewpaths_sh[0])

/* CorkscrewPath_Update (CorkscrewPath.c:12-72), reduced to the branch that
 * can ever actually execute.
 *
 * self->activePlayers is DEAD CODE in the original source itself, not a
 * simplification this port invented -- verified against the literal control
 * flow: activePlayers starts at 0 (never initialized nonzero anywhere in
 * CorkscrewPath_Create), and the ONLY statement in the entire file that ever
 * sets a bit into it is line 54 (`self->activePlayers |= playerID;`), which
 * sits inside the `else if` reached only when `(playerID & self->
 * activePlayers)` is ALREADY true (the outer `if (!(playerID & self->
 * activePlayers)) {...} else if (...) {...}` at lines 29/53). A bit that is
 * only ever set inside a branch that requires itself to already be set can
 * never transition away from 0 -- so lines 53-69 (the "already active, keep
 * riding" branch) can never run for any player, ever, and every actual
 * effect the object has flows entirely through the `if (!(playerID &
 * self->activePlayers))` branch (lines 29-52), which is unconditionally
 * true given activePlayers is provably always 0. Both branches apply
 * IDENTICAL physics when they fire (compare lines 33-48 to 53-68 -- same
 * position/velocity/onGround/animation writes, just gated by a slightly
 * different entry condition: the dead branch additionally requires
 * `player->velocity.y > -0x40000`), so nothing is lost by collapsing to the
 * one reachable path -- this is not a behavioral change, it is deleting
 * code that could never run.
 *
 * groundedStore -> onGround: `player->groundedStore` (CorkscrewPath.c:33,53)
 * is Player_Update's own snapshot of onGround taken BEFORE that same tick's
 * movement/collision resolution runs (Global/Player.c, `self->groundedStore
 * = self->onGround;` immediately before RSDK.ProcessObjectMovement). This
 * port has no such snapshot field (player.h has no groundedStore) --
 * corkscrew_path_apply() runs from s_main.c AFTER player_update() has
 * already fully resolved this tick's physics, same call-site convention
 * spring_apply()/force_spin_apply()/plane_switch_apply() already use, so
 * p->e.onGround here already reflects THIS tick's post-resolution grounded
 * state rather than the pre-resolution snapshot the original reads. A
 * same-tick timing simplification (both values are "was I on the ground
 * this tick", captured at very slightly different points within it), not a
 * different rule -- flagged rather than assumed identical.
 *
 * Animation (ANI_SPRING_CS) and the FLIP_Y facing bit are CUT entirely --
 * see corkscrew_path.h's own top comment for why (no converted asset, no
 * data field). `frame`/`CorkscrewPath->frameTable[]` (CorkscrewPath.c:26,
 * 41,62 and CorkscrewPath.h:9) existed only to feed that cut animation call,
 * so neither is computed here at all. */
/* NOT windowed by a binary search (2026-08-18 camera-X gating task): only 2
 * entries in this stage's own data (CORKSCREWPATH_COUNT), and the loop below
 * already carries its own exact per-entry distance bail (`if ((iabs(dx) >>
 * 16) > xSize) continue;`, cheaper than a search over a 2-element table
 * could ever be). */
void corkscrew_path_apply(Player *p)
{
	uint32_t i;

	for (i = 0; i < CORKSCREWPATH_COUNT; i++) {
		const CorkscrewPathDef *m = &k_paths[i];
		int32_t period = iabs((int32_t)m->period);        /* CorkscrewPath_Create:86 */
		int32_t xSize = period >> 1;                       /* CorkscrewPath_Create:87 */
		int32_t amplitude = (int32_t)m->amplitude << 6;     /* CorkscrewPath_Create:85 */
		int32_t mx = TO_FIXED(m->x), my = TO_FIXED(m->y);
		int32_t dx = p->e.x - mx;
		int32_t corkscrewPos, yOffset;

		if ((iabs(dx) >> 16) > xSize) continue;

		corkscrewPos = xSize + (dx >> 16);
		yOffset = amplitude * cos1024((corkscrewPos << 10) / period);

		if (iabs(yOffset + my - p->e.y) >= 0x100000) continue;

		if (!(iabs(p->e.groundVel) > 0x40000 && p->e.velY > -0x40000 && p->e.onGround))
			continue;

		p->e.y = my + yOffset;
		p->e.velY = 0;
		p->e.onGround = 1;
	}
}
