#include <stdint.h>
#include "spikes.h"

#define TO_FIXED(x) ((int32_t)(x) << 16)

/* assets/ghz/spikes.bin's own row shape (tools/convert_objects.py's
 * SPIKES_SCENE, Spikes_Serialize order, Spikes.c:749-757), byte-identical to
 * md_src/spikes.c's own SpikeEntry -- see that file's comment; this SH2 side
 * reads the SAME generated bytes through the linked-in `_ghz_spikes_sh`
 * label, same convention sh_src/spring.c's own k_springs already uses. */
typedef struct {
    int16_t x, y;
    uint8_t type, moving, count, stagger, timer, planeFilter;
} SpikeDef;

extern const uint16_t ghz_spikes_sh[];
static const SpikeDef *const k_spikes = (const SpikeDef *)((const uint8_t *)ghz_spikes_sh + 2);
#define SPIKES_COUNT (ghz_spikes_sh[0])

#define C_NONE   0
#define C_TOP    1
#define C_LEFT   2
#define C_RIGHT  3
#define C_BOTTOM 4

/* Precomputed once, mirroring md_src/spikes.c's own spikeSide[]/spikeVert[]
 * (see that file's comment for the type-bit decode, Spikes_Create:342-378). */
#define SPIKES_MAX 64   /* headroom above the converted 41; sized generously
                          * since this table is tiny (64 bytes each). */
static uint8_t spikeSide[SPIKES_MAX];
static uint8_t spikeVert[SPIKES_MAX];
static uint8_t spikeCountPx[SPIKES_MAX];   /* clamped count, Spikes.c:325-326 */
static uint8_t spikeShown[SPIKES_MAX];
static uint8_t spikesInit;

#define SPIKE_HIDDEN 0
#define SPIKE_SHOWN  1

/* This CPU's own local tick counter -- see md_src/spikes.c's own header
 * comment for why each side keeps an independent copy rather than sharing
 * one over the comm protocol. */
static uint32_t hazardTick;

static void spikes_setup(void)
{
    uint16_t i, n = SPIKES_COUNT;
    if (n > SPIKES_MAX) n = SPIKES_MAX;
    for (i = 0; i < n; i++) {
        const SpikeDef *e = &k_spikes[i];
        uint8_t dir = (uint8_t)(e->type & 1);
        uint8_t orient = (uint8_t)((e->type >> 1) & 1);
        uint8_t count = e->count;
        if (count < 2) count = 2;
        spikeCountPx[i] = count;
        spikeVert[i] = (uint8_t)(orient == 0);
        if (orient == 0) spikeSide[i] = dir ? C_BOTTOM : C_TOP;
        else              spikeSide[i] = dir ? C_LEFT : C_RIGHT;
        spikeShown[i] = e->moving ? SPIKE_HIDDEN : SPIKE_SHOWN;
    }
    spikesInit = 1;
}

static void spikes_tick_advance(void)
{
    uint16_t i, n = SPIKES_COUNT;
    if (n > SPIKES_MAX) n = SPIKES_MAX;
    hazardTick++;
    for (i = 0; i < n; i++) {
        const SpikeDef *e = &k_spikes[i];
        uint8_t matched;
        if (!e->moving) continue;
        matched = (uint8_t)(((hazardTick & 0x3F) == e->timer) &&
                            (((hazardTick & 0x40) != 0) == (e->stagger != 0)));
        if (matched) spikeShown[i] = (uint8_t)(spikeShown[i] ^ 1);
    }
}

/* Player_CheckCollisionBox / RSDK CheckObjectCollisionBox(setValues=true)
 * (Collision.cpp:276-461) -- transcribed identically to sh_src/spring.c's
 * own spring_check_box() (see that function's own derivation comment for
 * the full reasoning: symmetric hitboxes on both operands make the flip
 * transform a provable no-op, so it is not carried here either). Kept as
 * its own copy rather than shared -- same convention every physics file in
 * this directory already follows, no cross-file collision helper exists. */
static uint8_t spikes_check_box(Player *p, int32_t sx, int32_t sy,
                                int8_t hbLeft, int8_t hbTop, int8_t hbRight, int8_t hbBottom)
{
    int8_t oL = p->e.outer.left, oT = p->e.outer.top;
    int8_t oR = p->e.outer.right, oB = p->e.outer.bottom;
    int32_t thisIX = sx >> 16, thisIY = sy >> 16;
    int32_t otherIX = p->e.x >> 16, otherIY = p->e.y >> 16;
    int32_t collideX = p->e.x, collideY = p->e.y;
    uint8_t sideH = C_NONE, sideV = C_NONE, side;
    int32_t cx, cy;

    if (otherIX <= (hbRight + hbLeft + 2 * thisIX) >> 1) {
        if (otherIX + oR >= thisIX + hbLeft
            && thisIY + hbTop < otherIY + oB - 1
            && thisIY + hbBottom > otherIY + oT + 1) {
            sideH = C_LEFT;
            collideX = sx + TO_FIXED(hbLeft - oR);
        }
    } else {
        if (otherIX + oL < thisIX + hbRight
            && thisIY + hbTop < otherIY + oB - 1
            && thisIY + hbBottom > otherIY + oT + 1) {
            sideH = C_RIGHT;
            collideX = sx + TO_FIXED(hbRight - oL);
        }
    }

    if (otherIY < (hbTop + hbBottom + 2 * thisIY) >> 1) {
        if (otherIY + oB >= thisIY + hbTop
            && thisIX + hbLeft < otherIX + oR - 1
            && thisIX + hbRight > otherIX + oL + 1) {
            sideV = C_TOP;
            collideY = sy + TO_FIXED(hbTop - oB);
        }
    } else {
        if (otherIY + oT < thisIY + hbBottom
            && thisIX + hbLeft < otherIX + oR - 1) {
            if (otherIX + oL + 1 < thisIX + hbRight) {
                sideV = C_BOTTOM;
                collideY = sy + TO_FIXED(hbBottom - oT);
            }
        }
    }

    cx = (collideX - p->e.x) >> 16;
    cy = (collideY - p->e.y) >> 16;
    if ((cx * cx >= cy * cy && (sideV || !sideH)) || (!sideH && sideV))
        side = sideV;
    else
        side = sideH;

    switch (side) {
    case C_TOP:
        p->e.y = collideY;
        if (p->e.velY > 0) p->e.velY = 0;
        if (!p->e.onGround && p->e.velY >= 0) {
            p->e.groundVel = p->e.velX;
            p->e.angle = 0;
            p->e.onGround = 1;
        }
        p->controlLock = 0;
        p->e.collisionMode = CMODE_FLOOR;
        break;
    case C_LEFT:
        p->e.x = collideX;
        p->controlLock = 0;
        break;
    case C_RIGHT:
        p->e.x = collideX;
        p->controlLock = 0;
        break;
    case C_BOTTOM:
        p->e.y = collideY;
        if (p->e.velY < 0) p->e.velY = 0;
        break;
    default:
        break;
    }
    return side;
}

/* Spikes_Update's #if MANIA_USE_PLUS per-side gate (Spikes.c:125-161) --
 * Mighty/Ice branches dropped (see spikes.h's own header comment), reducing
 * each case to "does this side's own velocity-direction gate allow a hit
 * this tick, and does the resolved side match this spike's own dangerous
 * side (self->type)". moveOffset==TO_FIXED(8) (APPEAR) is this port's
 * SPIKE_HIDDEN/SPIKE_SHOWN toggle's own collapsed slide -- see this file's
 * header comment -- so the "or currently appearing" half of each gate below
 * is simply omitted: a spike is either fully SHOWN (gate applies normally)
 * or fully HIDDEN (skipped entirely, above this function). */
/* Player-proximity gate for spikes_apply()'s own SECOND loop (the collision
 * test below) ONLY -- never for spikes_tick_advance() above, which must run
 * for every entry every tick regardless of the player's position:
 * spikeShown[i] ^= 1 is an edge-triggered toggle (Spikes.c's own moving-spike
 * appear/retract schedule), not a value recomputed fresh from hazardTick, so
 * skipping an entry on the exact tick its own (hazardTick&0x3F)==e->timer
 * match fires would permanently desync that spike's shown/hidden phase from
 * every tick after -- a real correctness bug this file's own comment on
 * spikes_tick_advance() does not warn about but this gate must still respect.
 * The collision loop below has no such hazard: it only ever READS the
 * already-current spikeShown[i] and calls player_hit(), which cannot matter
 * while the player is outside touching range anyway.
 *
 * ghz_spikes_sh is x-sorted ascending (write_scene_table, same convention
 * every generated table in this batch uses) and SpikeDef's own sizeof (10,
 * matching SPIKES_SCENE's row_fmt ">hhBBBBBB" exactly -- verified against
 * this project's actual sh-elf-gcc, not assumed) has none of spikelog.c's
 * own odd-row padding hazard (see that file's own header comment), so a
 * direct k_spikes[m].x read is safe here.
 *
 * SPIKES_GATE_MARGIN: this stage's own converted data (assets/ghz/spikes.bin)
 * has count up to 20, and a vertical spike's hbL/hbR is +-8*count -> 160px
 * (the widest reach any entry in this table has); 160 + ~64 (player hitbox
 * + buffer) rounds up to 256. */
#define SPIKES_GATE_MARGIN 256

static void spikes_window(int32_t playerXpx, uint16_t n, uint16_t *lo, uint16_t *hi)
{
	int32_t xloWant = playerXpx - SPIKES_GATE_MARGIN;
	int32_t xhiWant = playerXpx + SPIKES_GATE_MARGIN;
	uint16_t a, b, m;

	a = 0; b = n;
	while (a < b) {
		m = (uint16_t)(a + (b - a) / 2);
		if (k_spikes[m].x < xloWant) a = (uint16_t)(m + 1); else b = m;
	}
	*lo = a;

	a = *lo; b = n;
	while (a < b) {
		m = (uint16_t)(a + (b - a) / 2);
		if (k_spikes[m].x < xhiWant) a = (uint16_t)(m + 1); else b = m;
	}
	*hi = a;
}

static void spikes_check_hit(Player *p, uint8_t side, int32_t hazardWorldX)
{
    /* Spikes_CheckHit's tail (Spikes.c:634-639), the Mighty branch removed:
     * away-from-hazard knockback direction, then player_hit()'s own
     * re-entrancy guard (already-hurt/dying/blinking) covers the rest of
     * Spikes_CheckHit's own early-return checks (state==Hurt,
     * invincibleTimer/blinkTimer>0 -- invincibleTimer does not exist in this
     * port, no shield/invincibility system). */
    (void)side;
    player_hit(p, hazardWorldX);
}

void spikes_apply(Player *p)
{
    uint32_t n = SPIKES_COUNT;
    uint16_t i, lo, hi;

    if (!spikesInit) spikes_setup();
    if (n > SPIKES_MAX) n = SPIKES_MAX;

    /* Ungated: every entry's own toggle schedule must keep running
     * regardless of the player's position -- see spikes_window()'s own
     * comment above for why. */
    spikes_tick_advance();

    spikes_window(p->e.x >> 16, (uint16_t)n, &lo, &hi);

    for (i = lo; i < hi; i++) {
        const SpikeDef *e = &k_spikes[i];
        int32_t sx, sy;
        int8_t hbL, hbT, hbR, hbB;
        uint8_t side, count;

        if (spikeShown[i] != SPIKE_SHOWN) continue;   /* Spikes.c:78 gate */

        sx = TO_FIXED(e->x);
        sy = TO_FIXED(e->y);
        count = spikeCountPx[i];

        /* Spikes_Create:355-358/373-376. */
        if (spikeVert[i]) { hbL = (int8_t)(-8 * count); hbT = -16; hbR = (int8_t)(8 * count); hbB = 16; }
        else              { hbL = -16; hbT = (int8_t)(-8 * count); hbR = 16; hbB = (int8_t)(8 * count); }

        side = spikes_check_box(p, sx, sy, hbL, hbT, hbR, hbB);
        if (side == C_NONE) continue;

        /* Spikes.c:125-158: velocity-direction gate per side (moveOffset==
         * APPEAR half dropped, see this function group's own header
         * comment), then the self->type match. */
        switch (side) {
        case C_TOP:    if (p->e.velY >= 0 && side == spikeSide[i]) spikes_check_hit(p, side, sx); break;
        case C_LEFT:   if (p->e.velX >= 0 && side == spikeSide[i]) spikes_check_hit(p, side, sx); break;
        case C_RIGHT:  if (p->e.velX <= 0 && side == spikeSide[i]) spikes_check_hit(p, side, sx); break;
        case C_BOTTOM: if (p->e.velY <= 0 && side == spikeSide[i]) spikes_check_hit(p, side, sx); break;
        default: break;
        }
    }
}
