#include <stdint.h>
#include "spring.h"

#define TO_FIXED(x) ((int32_t)(x) << 16)

static int32_t iabs(int32_t v)
{
	return v < 0 ? -v : v;
}

/* Spring's own editable fields, cut down to what this port's table needs.
 * x,y: px, Spring->position pre-TO_FIXED. type: Spring->type (0-5: vertical
 * yellow/red, horizontal yellow/red, diagonal yellow/red -- Spring_Create's
 * `self->type %= 6`, Spring.c:44). flipFlag: Spring->flipFlag, the raw
 * editor value (0 NONE, 1 X, 2 Y, 3 XY -- Drawing.hpp's FlipFlags), also
 * Spring->direction (Spring_Create:65/83/101 all set self->direction =
 * self->flipFlag verbatim).
 *
 * Not stored: planeFilter and onGround. Every one of GHZ1's 35 Mania-mode
 * Spring entities has planeFilter=0 (verified against the scene dump), so
 * Spring_State_*'s `!self->planeFilter || ...` gate is always true and is
 * not transcribed. onGround is more subtle: it is NOT all-zero in the scene
 * data (3 of the 35 -- all vertical-type entries, where the field is dead,
 * see below -- carry onGround=1), but Spring_State_Horizontal is the only
 * state that ever reads self->onGround (`!self->onGround || player->onGround`,
 * Spring.c:216/259), and every horizontal-type (type>>1==1) entry among the
 * 35 has onGround=0, which makes that gate's first operand unconditionally
 * true regardless of player->onGround -- so the gate collapses to "always
 * true" for every marker where it is ever actually evaluated, and is not
 * transcribed either. Spring_State_Vertical/Diagonal never read
 * self->onGround at all, so its value on the vertical/diagonal rows is
 * inert data, consistent with those 3 nonzero rows all being vertical-type. */
typedef struct {
	int16_t x, y;
	uint8_t type;
	uint8_t flipFlag;
} SpringDef;

/* GHZ Scene1.bin's Spring entities, Mania filter (filter & 3 != 0, same rule
 * convert_rings.py/force_spin.c/plane_switch.c all use) -- previously a
 * HAND-TRANSCRIBED 35-row copy of the exact same table tools/
 * convert_springs.py already generates as assets/ghz/springs.bin (two
 * independently-produced copies of one table, free to drift apart silently:
 * the 68000 side, md_src/springs.c, already read the generated table
 * through a fixed pointer; this SH2 side hand-typed its own). Deleted: this
 * now reads the SAME generated bytes directly, at their own linked address
 * (SH2s see the cartridge linearly, no banked window, no bank_select() --
 * see tools/gen_assets.py's own header comment), through the default
 * `_ghz_springs_sh` debug label that generator's assets_gen.s emits for
 * every manifest entry with no sh_link_name override.
 *
 * assets/ghz/springs.bin's own layout (tools/convert_springs.py: big-endian
 * u16 count, then that many entries of int16 x, int16 y, uint8 type, uint8
 * flipFlag, ascending by x) is byte-for-byte SpringDef's own shape below, so
 * the generated table is read in place with a cast, no copy -- ascending BY
 * X rather than the original's ascending-by-scene-slot order this file used
 * to keep k_springs in, which is fine: nothing here depends on scene slot
 * order (unlike force_spin.c/plane_switch.c's own placement in s_main.c,
 * whose ordering-sensitivity is about the PLAYER's slot always sitting
 * ahead of every entity checked here -- true regardless of which order the
 * springs themselves are visited in, since every iteration below is
 * independent of every other). */
extern const uint16_t ghz_springs_sh[];
static const SpringDef *const k_springs =
	(const SpringDef *)((const uint8_t *)ghz_springs_sh + 2);
#define SPRING_COUNT (ghz_springs_sh[0])

/* Collision.cpp's C_* result codes (RSDK.CheckObjectCollisionBox's return). */
#define C_NONE   0
#define C_TOP    1
#define C_LEFT   2
#define C_RIGHT  3
#define C_BOTTOM 4

/* RSDK.CheckObjectCollisionBox(entity=spring, entityHitbox, player,
 * playerHitbox, setValues=true) (Collision.cpp:276-461), thisEntity=spring
 * (sx,sy, hbLeft..hbBottom), otherEntity=player (p->e). Both boxes' FLIP_X/
 * FLIP_Y mirror (Collision.cpp:287-305, 354-372) is not transcribed: every
 * spring hitbox this port converts is symmetric (left==-right, top==-bottom
 * for all three of vertical/horizontal/diagonal, Spring_Create:74-77/92-95/
 * 116-119) and every generated Sonic hitbox is too (rings.c's own verified
 * note against sonic_data.c/the outer box RSDK.GetHitbox returns), so the
 * flip transform is provably a no-op on both operands here, same reasoning
 * rings.c's ring_touches_sonic already documents for the touch-test cousin
 * of this function.
 *
 * otherHitbox->top++/bottom-- (Collision.cpp:312-313) shrinks the player's
 * box by 1px top and bottom, but ONLY for the H-test's Y-overlap gate below;
 * otherHitbox->left++/right-- (330,332) is the V-test's mirror, shrinking by
 * 1px left/right for the V-test's X-overlap gate -- neither shrink ever
 * reaches the collideX/collideY formulas themselves (those always read the
 * player's true, unshrunk box), so this port applies the +-1 inline in the
 * two gates below rather than mutating any stored box. */
static uint8_t spring_check_box(Player *p, int32_t sx, int32_t sy,
                                int8_t hbLeft, int8_t hbTop, int8_t hbRight, int8_t hbBottom)
{
	int8_t oL = p->e.outer.left, oT = p->e.outer.top;
	int8_t oR = p->e.outer.right, oB = p->e.outer.bottom;
	int32_t thisIX = sx >> 16, thisIY = sy >> 16;
	int32_t otherIX = p->e.x >> 16, otherIY = p->e.y >> 16;
	int32_t collideX = p->e.x, collideY = p->e.y;
	uint8_t sideH = C_NONE, sideV = C_NONE, side;
	int32_t cx, cy;

	/* H-test (Collision.cpp:315-328): otherHitbox top/bottom shrunk by 1. */
	if (otherIX <= (hbRight + hbLeft + 2 * thisIX) >> 1) {
		if (otherIX + oR >= thisIX + hbLeft
		    && thisIY + hbTop < otherIY + oB - 1
		    && thisIY + hbBottom > otherIY + oT + 1) {
			sideH = C_LEFT;
			collideX = sx + TO_FIXED(hbLeft - oR);
		}
	} else {
		if (otherIX + oL < thisIX + hbRight
		    && thisIY + hbTop < otherIY + oB - 1
		    && thisIY + hbBottom > otherIY + oT + 1) {
			sideH = C_RIGHT;
			collideX = sx + TO_FIXED(hbRight - oL);
		}
	}

	/* V-test (Collision.cpp:335-349): otherHitbox left/right shrunk by 1
	 * (top/bottom are back to their true values -- the H-test's shrink was
	 * undone before this, Collision.cpp:330-333). */
	if (otherIY < (hbTop + hbBottom + 2 * thisIY) >> 1) {
		if (otherIY + oB >= thisIY + hbTop
		    && thisIX + hbLeft < otherIX + oR - 1
		    && thisIX + hbRight > otherIX + oL + 1) {
			sideV = C_TOP;
			collideY = sy + TO_FIXED(hbTop - oB);
		}
	} else {
		if (otherIY + oT < thisIY + hbBottom
		    && thisIX + hbLeft < otherIX + oR - 1) {
			if (otherIX + oL + 1 < thisIX + hbRight) {
				sideV = C_BOTTOM;
				collideY = sy + TO_FIXED(hbBottom - oT);
			}
		}
	}

	/* Side pick (Collision.cpp:376-383): larger true penetration wins, a
	 * tie (or a lone axis) prefers V. */
	cx = (collideX - p->e.x) >> 16;
	cy = (collideY - p->e.y) >> 16;
	if ((cx * cx >= cy * cy && (sideV || !sideH)) || (!sideH && sideV))
		side = sideV;
	else
		side = sideH;

	/* setValues=true's application (Collision.cpp:385-461), RETRO_REV0U's
	 * tileCollisions!=TILECOLLISION_UP branch always taken (this port never
	 * runs upside-down gravity, same reduction path.c's own top comment
	 * documents for the position finders). */
	switch (side) {
	case C_TOP:
		p->e.y = collideY;
		if (p->e.velY > 0) p->e.velY = 0;
		if (!p->e.onGround && p->e.velY >= 0) {
			p->e.groundVel = p->e.velX;
			p->e.angle = 0;
			p->e.onGround = 1;
		}
		/* Player_CheckCollisionBox's own wrapper (Player.c:2281-2283):
		 * controlLock=0, collisionMode=CMODE_FLOOR. The sensorX/flailing
		 * bookkeeping right after (Player.c:2285-2313) is not ported --
		 * nothing in this port ever reads player->flailing or
		 * collisionFlagV, so it has no observable effect (rings.c's
		 * spawn_sparkle comment documents the same "computed upstream but
		 * provably unused here" shape for a different field). */
		p->controlLock = 0;
		p->e.collisionMode = CMODE_FLOOR;
		break;
	case C_LEFT:
		p->e.x = collideX;
		/* Player_CheckCollisionBox's C_LEFT wrapper (Player.c:2317-2330):
		 * controlLock=0 always; the "player->left && onGround" bump
		 * (groundVel=-0x8000, position.x&=0xFFFF0000) is the reference's
		 * own documented spindash bug (Player.c:2320-2327) -- this port
		 * has no spindash, and every spring type that can resolve to
		 * C_LEFT is a horizontal spring whose own state handler
		 * unconditionally overwrites groundVel/velocity.x again this
		 * same frame when the collision is the launching side (Spring.c:
		 * 216-251), so a same-frame -0x8000 nudge here is always either
		 * dead (launching side) or a no-op the caller ignores (non-
		 * launching side, C_LEFT/C_RIGHT swapped) -- not transcribed. */
		p->controlLock = 0;
		break;
	case C_RIGHT:
		p->e.x = collideX;
		p->controlLock = 0;
		break;
	case C_BOTTOM:
		p->e.y = collideY;
		if (p->e.velY < 0) p->e.velY = 0;
		break;
	default:
		break;
	}
	return side;
}

/* Player_CheckCollisionTouch -> RSDK.CheckObjectCollisionTouchBox ->
 * CheckObjectCollisionTouch (Collision.cpp:209-274), used only by the
 * diagonal spring (Spring_State_Diagonal reads touch, not box). Same
 * symmetric-hitbox no-flip reasoning as spring_check_box(). */
static uint8_t spring_touches(Player *p, int32_t sx, int32_t sy,
                              int8_t hbLeft, int8_t hbTop, int8_t hbRight, int8_t hbBottom)
{
	int32_t thisIX = sx >> 16, thisIY = sy >> 16;
	int32_t otherIX = p->e.x >> 16, otherIY = p->e.y >> 16;

	return thisIX + hbLeft < otherIX + p->e.outer.right
	    && thisIX + hbRight > otherIX + p->e.outer.left
	    && thisIY + hbTop < otherIY + p->e.outer.bottom
	    && thisIY + hbBottom > otherIY + p->e.outer.top;
}

/* animationReserve's own selection (Spring.c:149-151/329-331, both vertical-
 * up and diagonal triggers share this exact snippet): keep the current anim
 * if it is already one of the run-cycle family, else default to WALK. */
static uint16_t spring_reserve_anim(uint16_t anim)
{
	if (anim == ANI_WALK || anim == ANI_JOG || anim == ANI_RUN || anim == ANI_DASH)
		return anim;
	return ANI_WALK;
}

/* Spring_State_Vertical (Spring.c:134-207). */
static void spring_vertical(Player *p, const SpringDef *m)
{
	int32_t sx = TO_FIXED(m->x), sy = TO_FIXED(m->y);
	int32_t velY = (m->type & 1) ? TO_FIXED(16) : TO_FIXED(10);
	uint8_t side;

	if (!m->flipFlag) velY = -velY;

	side = spring_check_box(p, sx, sy, -16, -8, 16, 8);

	if (m->flipFlag == 0) {
		/* direction == FLIP_NONE: an upward spring, checks C_TOP. */
		if (side != C_TOP) return;

		p->animationReserve = spring_reserve_anim(p->animator.anim);

		if (p->state == PSTATE_TUBE_ROLL || p->state == PSTATE_TUBE_AIR) {
			p->state = PSTATE_TUBE_AIR;
		} else {
			sonic_set_anim(&p->animator, ANI_SPRING_TWIRL, 1, 0);
			p->state = PSTATE_NORMAL;   /* Player_State_Air */
		}
	} else {
		/* direction != FLIP_NONE: a downward spring, checks C_BOTTOM. No
		 * animation change at all in this branch (Spring.c:183-206). */
		if (side != C_BOTTOM) return;

		if (p->state == PSTATE_TUBE_ROLL || p->state == PSTATE_TUBE_AIR)
			p->state = PSTATE_TUBE_AIR;
		else
			p->state = PSTATE_NORMAL;   /* Player_State_Air */
	}

	p->e.onGround = 0;
	p->e.velY = velY;
	/* tileCollisions = TILECOLLISION_DOWN: this port's path.c only ever
	 * runs "down" collision (no upside-down-gravity variant exists at all,
	 * see path.c's top comment), so this write is already this port's
	 * permanent state and is not transcribed as a field. */
}

/* Spring_State_Horizontal (Spring.c:208-298). */
static void spring_horizontal(Player *p, const SpringDef *m)
{
	int32_t sx = TO_FIXED(m->x), sy = TO_FIXED(m->y);
	int32_t velX = (m->type & 1) ? TO_FIXED(16) : TO_FIXED(10);
	uint8_t side, wantSide, direction;

	if (m->flipFlag) velX = -velX;

	side = spring_check_box(p, sx, sy, -8, -16, 8, 16);

	/* direction == FLIP_NONE checks C_RIGHT, else checks C_LEFT
	 * (Spring.c:216, 259); "!self->onGround || player->onGround"
	 * (Spring.c:216, 259) is always true here -- see SpringDef's own
	 * comment for why every horizontal-type row has onGround==0. */
	wantSide = m->flipFlag ? C_LEFT : C_RIGHT;
	direction = m->flipFlag ? 1 : 0;   /* FLIP_NONE=0/right, FLIP_X=1/left */
	if (side != wantSide) return;

	if (p->e.collisionMode == CMODE_ROOF) {
		p->e.velX = -velX;
		p->e.groundVel = -velX;
	} else {
		p->e.velX = velX;
		p->e.groundVel = p->e.velX;
	}

	if (p->state != PSTATE_ROLL && p->state != PSTATE_TUBE_AIR && p->state != PSTATE_TUBE_ROLL)
		p->state = PSTATE_NORMAL;   /* Ground or Air, off e.onGround */

	/* Direct animationID field write (Spring.c:234/277), NOT
	 * sonic_set_anim: frameID/timer/duration are deliberately left alone,
	 * matching RSDK.Animator's own animationID being a plain settable
	 * field distinct from frameID/timer there too. */
	if (p->animator.anim != ANI_JUMP && p->animator.anim != ANI_JOG
	    && p->animator.anim != ANI_RUN && p->animator.anim != ANI_DASH)
		p->animator.anim = ANI_WALK;

	p->controlLock = 16;
	p->skidding = 0;
	p->direction = direction;
	p->e.onGround = 0;
}

/* Spring_State_Diagonal (Spring.c:299-354). */
static void spring_diagonal(Player *p, const SpringDef *m)
{
	int32_t sx = TO_FIXED(m->x), sy = TO_FIXED(m->y);
	int32_t mag = (m->type & 1) ? 0xB4000 : 0x74000;
	int32_t velX = mag, velY = mag;
	uint8_t collided;

	if (m->flipFlag < 2) velY = -velY;               /* < FLIP_Y: up */
	if (m->flipFlag & 1) velX = -velX;                /* & FLIP_X: left */

	if (!spring_touches(p, sx, sy, -12, -12, 12, 12)) return;

	if (p->e.onGround || p->e.velY >= 0)
		collided = 1;
	else
		collided = iabs(p->e.velX) > -p->e.velY;
	if (!collided) return;

	if (p->state == PSTATE_TUBE_ROLL || p->state == PSTATE_TUBE_AIR) {
		p->state = PSTATE_TUBE_AIR;
	} else {
		p->state = PSTATE_NORMAL;   /* Player_State_Air */
		if (p->animator.anim != ANI_JUMP && p->animator.anim != ANI_JOG
		    && p->animator.anim != ANI_RUN && p->animator.anim != ANI_DASH)
			p->animator.anim = ANI_WALK;
	}

	if (m->flipFlag < 2) {   /* self->direction < FLIP_Y */
		if (p->state != PSTATE_TUBE_ROLL && p->state != PSTATE_TUBE_AIR) {
			p->animationReserve = spring_reserve_anim(p->animator.anim);
			sonic_set_anim(&p->animator, ANI_SPRING_DIAGONAL, 1, 0);
		}
	}

	p->direction = (uint8_t)(m->flipFlag & 1);
	p->e.onGround = 0;
	p->e.velX = velX;
	p->e.velY = velY;
}

void spring_apply(Player *p)
{
	uint32_t i;

	for (i = 0; i < SPRING_COUNT; i++) {
		const SpringDef *m = &k_springs[i];

		switch (m->type >> 1) {
		case 0: spring_vertical(p, m); break;
		case 1: spring_horizontal(p, m); break;
		default: spring_diagonal(p, m); break;
		}
	}
}
