/* Generated by tools/convert_objects.py. Do not edit by hand. */

#ifndef BATBRAIN_DATA_H
#define BATBRAIN_DATA_H

#include <stdint.h>
#include "obj_data.h"

#define BATBRAIN_PAL 0
#define BATBRAIN_MAX_FRAME_TILES  17
#define BATBRAIN_MAX_FRAME_PIECES 2

extern const ObjFrame batbrain_hang[1];
extern const ObjFrame batbrain_fly[1];
extern const ObjPiece batbrain_pieces[];

#endif
