/* Generated by tools/convert_objects.py. Do not edit by hand. */

#include "batbrain_data.h"

const ObjPiece batbrain_pieces[] = {
    { 0, 0, 6, 0 },
    { 0, 0, 15, 0 },
    { 32, 8, 0, 16 },
};

const ObjFrame batbrain_hang[1] = {
    { 0, 0, 6, 1, -7, -12, 0 },
};

const ObjFrame batbrain_fly[1] = {
    { 6, 1, 17, 2, -15, -6, 2 },
};
