/* Generated by tools/convert_objects.py. Do not edit by hand. */

#include "bridge_data.h"

const ObjPiece bridge_pieces[] = {
    { 0, 0, 5, 0 },
};

const ObjFrame bridge_log[1] = {
    { 0, 0, 4, 1, -8, -8, 0 },
};
