/* Generated by tools/convert_objects.py. Do not edit by hand. */

#ifndef BRIDGE_DATA_H
#define BRIDGE_DATA_H

#include <stdint.h>
#include "obj_data.h"

#define BRIDGE_PAL 0
#define BRIDGE_MAX_FRAME_TILES  4
#define BRIDGE_MAX_FRAME_PIECES 1

extern const ObjFrame bridge_log[1];
extern const ObjPiece bridge_pieces[];

#endif
