/* Generated by tools/convert_objects.py. Do not edit by hand. */

#include "buzzbomber_data.h"

const ObjPiece buzzbomber_pieces[] = {
    { 0, 0, 14, 0 },
    { 32, 0, 6, 12 },
};

const ObjFrame buzzbomber_fly[1] = {
    { 0, 0, 18, 2, -23, -9, 256 },
};
