/* Generated by tools/convert_objects.py. Do not edit by hand. */

#ifndef BUZZBOMBER_DATA_H
#define BUZZBOMBER_DATA_H

#include <stdint.h>
#include "obj_data.h"

#define BUZZBOMBER_PAL 0
#define BUZZBOMBER_MAX_FRAME_TILES  19
#define BUZZBOMBER_MAX_FRAME_PIECES 2

extern const ObjFrame buzzbomber_fly[1];
extern const ObjFrame buzzbomber_shoot[11];
extern const ObjFrame buzzbomber_wings[4];
extern const ObjFrame buzzbomber_thrust[4];
extern const ObjFrame buzzbomber_projectile[12];
extern const ObjPiece buzzbomber_pieces[];

#endif
