/* Generated by tools/convert_objects.py. Do not edit by hand. */

#include "chopper_data.h"

const ObjPiece chopper_pieces[] = {
    { 0, 0, 15, 0 },
    { 0, 0, 15, 0 },
};

const ObjFrame chopper_jump[2] = {
    { 0, 0, 16, 1, -15, -16, 4 },
    { 16, 1, 16, 1, -15, -16, 4 },
};
