/* Generated by tools/convert_objects.py. Do not edit by hand. */

#ifndef CHOPPER_DATA_H
#define CHOPPER_DATA_H

#include <stdint.h>
#include "obj_data.h"

#define CHOPPER_PAL 3
#define CHOPPER_MAX_FRAME_TILES  16
#define CHOPPER_MAX_FRAME_PIECES 1

extern const ObjFrame chopper_jump[2];
extern const ObjPiece chopper_pieces[];

#endif
