/* Generated by tools/convert_objects.py. Do not edit by hand. */

#ifndef CRABMEAT_DATA_H
#define CRABMEAT_DATA_H

#include <stdint.h>
#include "obj_data.h"

#define CRABMEAT_PAL 3
#define CRABMEAT_MAX_FRAME_TILES  24
#define CRABMEAT_MAX_FRAME_PIECES 2

extern const ObjFrame crabmeat_stand[1];
extern const ObjFrame crabmeat_walk[7];
extern const ObjFrame crabmeat_shoot[8];
extern const ObjFrame crabmeat_projectile[6];
extern const ObjPiece crabmeat_pieces[];

#endif
