/* Generated by tools/convert_objects.py. Do not edit by hand. */

#include "crabmeat_data.h"

const ObjPiece crabmeat_pieces[] = {
    { 0, 0, 15, 0 },
    { 32, 0, 7, 16 },
    { 0, 0, 15, 0 },
    { 32, 0, 7, 16 },
};

const ObjFrame crabmeat_walk[2] = {
    { 0, 0, 24, 2, -22, -15, 6 },
    { 24, 2, 24, 2, -22, -15, 6 },
};
