/* Generated by tools/convert_objects.py. Do not edit by hand. */

#ifndef DECORATION_DATA_H
#define DECORATION_DATA_H

#include <stdint.h>
#include "obj_data.h"

#define DECORATION_PAL 0
#define DECORATION_MAX_FRAME_TILES  8
#define DECORATION_MAX_FRAME_PIECES 1

extern const ObjFrame decoration_bridgepost[1];
extern const ObjPiece decoration_pieces[];

#endif
