/* Generated by tools/convert_objects.py. Do not edit by hand. */

#include "decoration_data.h"

const ObjPiece decoration_pieces[] = {
    { 0, 0, 13, 0 },
};

const ObjFrame decoration_bridgepost[1] = {
    { 0, 0, 8, 1, -16, -8, 0 },
};
