/* Generated by tools/convert_objects.py. Do not edit by hand. */

#ifndef ITEMBOX_DATA_H
#define ITEMBOX_DATA_H

#include <stdint.h>
#include "obj_data.h"

#define ITEMBOX_PAL 0
#define ITEMBOX_MAX_FRAME_TILES  16
#define ITEMBOX_MAX_FRAME_PIECES 1

extern const ObjFrame itembox_box[1];
extern const ObjFrame itembox_broken[1];
extern const ObjFrame itembox_contents[10];
extern const ObjPiece itembox_pieces[];

#endif
