/* Generated by tools/convert_objects.py. Do not edit by hand. */

#include "motobug_data.h"

const ObjPiece motobug_pieces[] = {
    { 0, 0, 15, 0 },
    { 32, 8, 1, 16 },
    { 0, 0, 15, 0 },
    { 32, 8, 1, 16 },
};

const ObjFrame motobug_move[2] = {
    { 0, 0, 18, 2, -20, -14, 2 },
    { 18, 2, 18, 2, -20, -15, 2 },
};
