/* Generated by tools/convert_objects.py. Do not edit by hand. */

#ifndef NEWTRON_DATA_H
#define NEWTRON_DATA_H

#include <stdint.h>
#include "obj_data.h"

#define NEWTRON_PAL 3
#define NEWTRON_MAX_FRAME_TILES  21
#define NEWTRON_MAX_FRAME_PIECES 3

extern const ObjFrame newtron_shootidle[1];
extern const ObjFrame newtron_fly[1];
extern const ObjPiece newtron_pieces[];

#endif
