/* Generated by tools/convert_objects.py. Do not edit by hand. */

#include "newtron_data.h"

const ObjPiece newtron_pieces[] = {
    { 0, 0, 15, 0 },
    { 0, 32, 4, 16 },
    { 32, 0, 2, 18 },
    { 0, 0, 13, 0 },
    { 32, 0, 1, 8 },
};

const ObjFrame newtron_shootidle[1] = {
    { 0, 0, 21, 3, -19, -20, 1 },
};

const ObjFrame newtron_fly[1] = {
    { 21, 3, 10, 2, -15, -18, 1 },
};
