/* Generated by tools/convert_objects.py. Do not edit by hand. */

#include "platform_data.h"

const ObjPiece platform_pieces[] = {
    { 0, 0, 15, 0 },
    { 32, 0, 7, 16 },
    { 0, 0, 13, 0 },
    { 32, 0, 5, 8 },
    { 0, 0, 5, 0 },
    { 0, 0, 5, 0 },
};

const ObjFrame platform_normal[1] = {
    { 0, 0, 24, 2, -24, -16, 256 },
};

const ObjFrame platform_swing[3] = {
    { 24, 2, 12, 2, -24, -8, 0 },
    { 36, 4, 4, 1, -8, -8, 0 },
    { 40, 5, 4, 1, -8, -8, 0 },
};
