/* Generated by tools/convert_objects.py. Do not edit by hand. */

#ifndef PLATFORM_DATA_H
#define PLATFORM_DATA_H

#include <stdint.h>
#include "obj_data.h"

#define PLATFORM_PAL 0
#define PLATFORM_MAX_FRAME_TILES  24
#define PLATFORM_MAX_FRAME_PIECES 2

extern const ObjFrame platform_normal[1];
extern const ObjFrame platform_swing[3];
extern const ObjPiece platform_pieces[];

#endif
