/* Generated by tools/convert_ring.py. Do not edit by hand. */

#ifndef RING_DATA_H
#define RING_DATA_H

#include <stdint.h>

/* Ring.c:170-175 (Ring_Collect): sparkle->maxFrameCount = frameCount-1,
 * frameCount halved first for animationID==2 (Sparkle 1). Precomputed here
 * since both operands are link-time constants; game/md_src/rings.c uses
 * these directly instead of re-deriving them from a raw frame count. */
#define RING_ANIM0_FRAMES      16   /* "Normal Ring", Ring.c:525 drives frameID directly */
#define RING_SPARKLE1_MAXFRAME 15   /* "Sparkle 1", RING_TYPE_SPARKLE1 == 2 */
#define RING_SPARKLE3_MAXFRAME 8   /* "Sparkle 3", RING_TYPE_SPARKLE3 == 4 */

/* Tile offsets into ring_tiles[], in tiles (4 tiles/frame, 2x2). */
#define RING_ANIM0_TILE_BASE     0
#define RING_SPARKLE1_TILE_BASE  64
#define RING_SPARKLE3_TILE_BASE  124
#define RING_TILE_COUNT          156

/* One of the four existing CRAM lines (PAL0-2 = assets/ghz/pal.bin, PAL3 =
 * assets/sonic/pal.bin); see this file's generator for the fit. */
#define RING_PAL 2

/* RSDK.ProcessAnimation's raw per-frame durations (Animation.cpp:150-176),
 * indices 0..RING_SPARKLE{1,3}_MAXFRAME-1, paired with the animator speed
 * RSDK.Rand(6,8) picks per sparkle (Ring.c:176). */
extern const uint16_t ring_sparkle1_durations[RING_SPARKLE1_MAXFRAME];
extern const uint16_t ring_sparkle3_durations[RING_SPARKLE3_MAXFRAME];

extern const uint32_t ring_tiles[];

#endif
