/* Generated by tools/convert_objects.py. Do not edit by hand. */

#include "ring_data.h"

const uint16_t ring_sparkle1_durations[RING_SPARKLE1_MAXFRAME] = { 8 };
const uint16_t ring_sparkle3_durations[RING_SPARKLE3_MAXFRAME] = { 16 };
