/* Generated by tools/convert_objects.py. Do not edit by hand. */

#ifndef RING_DATA_H
#define RING_DATA_H

#include <stdint.h>

#define RING_ANIM0_FRAMES      16
#define RING_SPARKLE1_MAXFRAME 15
#define RING_SPARKLE3_MAXFRAME 8

#define RING_ANIM0_TILE_BASE     0
#define RING_SPARKLE1_TILE_BASE  64
#define RING_SPARKLE3_TILE_BASE  124
#define RING_TILE_COUNT          156

#define RING_PAL 2

extern const uint16_t ring_sparkle1_durations[RING_SPARKLE1_MAXFRAME];
extern const uint16_t ring_sparkle3_durations[RING_SPARKLE3_MAXFRAME];

#endif
