/* Generated by tools/convert_objects.py. Do not edit by hand. */

#include "signpost_data.h"

const ObjPiece signpost_post_pieces[] = {
    { 0, 0, 0, 0 },
    { 0, 0, 3, 0 },
    { 0, 0, 9, 0 },
};

const ObjFrame signpost_post[3] = {
    { 0, 0, 1, 1, -3, -24, 0 }, /* Post Bits frame 0 */
    { 1, 1, 4, 1, -4, -22, 0 }, /* Post Bits frame 1 */
    { 5, 2, 6, 1, -12, 8, 0 }, /* Post Bits frame 2 */
};

const ObjPiece signpost_plate_pieces[] = {
    { 0, 0, 15, 0 },
    { 32, 0, 7, 16 },
    { 0, 0, 3, 0 },
    { 0, 0, 15, 0 },
    { 32, 0, 7, 16 },
    { 0, 0, 3, 0 },
};

const ObjFrame signpost_plate[2][SIGNPOST_PLATE_STEPS] = {
    { /* Sonic */
        { 0, 0, 24, 2, -24, -22, 0 },
        { 24, 2, 4, 1, -24, -22, 0 },
    },
    { /* Eggman */
        { 28, 3, 24, 2, -24, -22, 0 },
        { 52, 5, 4, 1, -24, -22, 0 },
    },
};
