/* Generated by tools/convert_objects.py. Do not edit by hand. */

#ifndef SIGNPOST_DATA_H
#define SIGNPOST_DATA_H

#include <stdint.h>
#include "obj_data.h"   /* ObjFrame/ObjPiece -- shared with spring_data.h. */

#define SIGNPOST_PLATE_STEPS 2
#define SIGNPOST_PAL_POST  0
#define SIGNPOST_PAL_FACE  0
#define SIGNPOST_MAX_RESIDENT_TILES  11
#define SIGNPOST_MAX_RESIDENT_PIECES 1
#define SIGNPOST_MAX_STREAM_TILES    24
#define SIGNPOST_MAX_STREAM_PIECES   2

#define SIGNPOST_SPRING_SHARED_WINDOW_TILES 24

extern const ObjFrame signpost_post[3];
extern const ObjPiece signpost_post_pieces[];

extern const ObjFrame signpost_plate[2][SIGNPOST_PLATE_STEPS];
extern const ObjPiece signpost_plate_pieces[];

#endif
