/* Generated by tools/convert_sonic.py. Do not edit by hand. */

#ifndef SONIC_DATA_H
#define SONIC_DATA_H

#include <stdint.h>

typedef struct {
    int8_t  dx, dy;       /* pixel offset from the frame's top left */
    uint8_t size;         /* ((w-1) << 2) | (h-1), the VDP sprite size field */
    uint8_t tile;         /* first tile, relative to the frame's tile block */
} SonicPiece;

typedef struct {
    uint16_t tileOffset;  /* into sonic_tiles, in tiles */
    uint16_t pieceOffset; /* into sonic_pieces */
    uint8_t  tileCount;
    uint8_t  pieceCount;
    int8_t   pivotX, pivotY;
    uint16_t duration;    /* RSDK frame duration, paired with the animator speed */
    int8_t   outerLeft, outerTop, outerRight, outerBottom;
    int8_t   innerLeft, innerTop, innerRight, innerBottom;
} SonicFrame;

typedef struct {
    uint16_t first;       /* first frame index */
    uint8_t  count;
    uint8_t  loop;
    int16_t  speed;
} SonicAnim;

enum { ANI_IDLE, ANI_WALK, ANI_JOG, ANI_RUN, ANI_DASH, ANI_SKID, ANI_SKID_TURN, ANI_AIR_WALK, ANI_JUMP, ANI_PUSH, ANI_LOOK_UP, ANI_CROUCH, ANI_SPRING_TWIRL, ANI_SPRING_DIAGONAL, ANI_HURT, ANI_DIE, SONIC_ANIM_COUNT };

#define SONIC_MAX_FRAME_TILES 33
#define SONIC_MAX_PIECES      4
#define SONIC_FRAME_COUNT     124   /* rows in hitbox.bin, and the
                                     * valid range of the comm frameIndex
                                     * (sh_src/comm.h's COMM_ANIM bits) */

extern const SonicPiece sonic_pieces[];
extern const SonicFrame sonic_frames[];
extern const SonicAnim  sonic_anims[SONIC_ANIM_COUNT];

/* sonic_pal/sonic_tiles are NOT declared here: they live in cartridge bank 1
 * (game/tools/gen_assets.py's manifest, ASSET_SONIC_PAL/ASSET_SONIC_TILES in
 * the generated game/md_src/assets_gen.h), reached from game/md_src/main.c
 * and game/md_src/sonic.c through that generated pointer instead of a
 * linked extern array -- see those files' own comments. */

#endif
