/* Generated by tools/convert_sonic.py. Do not edit by hand. */

#ifndef SONIC_ROT_DATA_H
#define SONIC_ROT_DATA_H

#include <stdint.h>
#include "sonic_data.h"

/* Baked rotated Sonic frames: three orientations (45, 90, 135 degrees) per
 * base frame of WALK/JOG/RUN/DASH/AIR_WALK, the ROTSTYLE_FULL animations
 * (see tools/convert_sonic.py's ROTATE_ANIMS comment and sh_src/player.h's
 * rotation field comment). Tile pixels live in assets/sonic/rot_tiles.bin,
 * linked into the SH2 program (sh_src/sonic_rot.s / sh_src/mars.ld's
 * sonicrot region) and read by the 68000 through the fixed pointer
 * sonic_rot_tiles_md (md_src/sonic.c) -- not through sonic_rot_tiles[] the
 * way sonic_tiles[] is linked in directly, since this data does not fit the
 * 68000's own 512 KB ROM window alongside everything else (same reasoning
 * as FG High's map, md_src/main.c's ghz_map_fgh_md comment). */

typedef struct {
    uint16_t tileOffset;  /* into sonic_rot_tiles_md, in tiles */
    uint16_t pieceOffset; /* into sonic_rot_pieces */
    uint8_t  tileCount;
    uint8_t  pieceCount;
    int8_t   pivotX, pivotY;
} SonicRotFrame;

/* Per-animation rotation-display class, indexed by the same absolute frame
 * index sonic_frames[]/COMM_ANIM's frameIndex use (md_src/sonic.c's
 * orientation-fold comment has the full per-class render rule):
 *   SONIC_ROTCLASS_NONE  ANI_JUMP/ANI_SKID/ANI_SKID_TURN -- rotation
 *                         computed (sh_src/player.c) but never displayed,
 *                         baked ROTSTYLE_NONE in the original sprite sheet.
 *   SONIC_ROTCLASS_R180   ANI_IDLE/ANI_PUSH/ANI_LOOK_UP/ANI_CROUCH --
 *                         flipH+flipV of the base frame when dispRot==4,
 *                         upright otherwise; no baked art (exact pixel op).
 *   SONIC_ROTCLASS_FULL   ANI_WALK/ANI_JOG/ANI_RUN/ANI_DASH/ANI_AIR_WALK --
 *                         the 8-orientation fold below, using the 3 baked
 *                         sets this file's tables carry. */
enum { SONIC_ROTCLASS_NONE, SONIC_ROTCLASS_R180, SONIC_ROTCLASS_FULL };

extern const uint8_t       sonic_rot_class[SONIC_FRAME_COUNT];
/* Index into sonic_rot_frames[] of the 45-degree entry for a SONIC_ROTCLASS_
 * FULL base frame (90 is +1, 135 is +2); -1 for every other frame. */
extern const int16_t       sonic_rot_index[SONIC_FRAME_COUNT];
extern const SonicPiece    sonic_rot_pieces[];
extern const SonicRotFrame sonic_rot_frames[];

#endif
