/* Generated by tools/convert_sonic.py. Do not edit by hand. */

#include "sonic_rot_data.h"

const uint8_t sonic_rot_class[SONIC_FRAME_COUNT] = {
    SONIC_ROTCLASS_R180, /* Idle frame 0 */
    SONIC_ROTCLASS_FULL, /* Walk frame 0 */
    SONIC_ROTCLASS_FULL, /* Walk frame 1 */
    SONIC_ROTCLASS_FULL, /* Walk frame 2 */
    SONIC_ROTCLASS_FULL, /* Walk frame 3 */
    SONIC_ROTCLASS_FULL, /* Walk frame 4 */
    SONIC_ROTCLASS_FULL, /* Walk frame 5 */
    SONIC_ROTCLASS_FULL, /* Walk frame 6 */
    SONIC_ROTCLASS_FULL, /* Walk frame 7 */
    SONIC_ROTCLASS_FULL, /* Walk frame 8 */
    SONIC_ROTCLASS_FULL, /* Walk frame 9 */
    SONIC_ROTCLASS_FULL, /* Walk frame 10 */
    SONIC_ROTCLASS_FULL, /* Walk frame 11 */
    SONIC_ROTCLASS_FULL, /* Jog frame 0 */
    SONIC_ROTCLASS_FULL, /* Jog frame 1 */
    SONIC_ROTCLASS_FULL, /* Jog frame 2 */
    SONIC_ROTCLASS_FULL, /* Jog frame 3 */
    SONIC_ROTCLASS_FULL, /* Jog frame 4 */
    SONIC_ROTCLASS_FULL, /* Jog frame 5 */
    SONIC_ROTCLASS_FULL, /* Jog frame 6 */
    SONIC_ROTCLASS_FULL, /* Jog frame 7 */
    SONIC_ROTCLASS_FULL, /* Jog frame 8 */
    SONIC_ROTCLASS_FULL, /* Jog frame 9 */
    SONIC_ROTCLASS_FULL, /* Run frame 0 */
    SONIC_ROTCLASS_FULL, /* Run frame 1 */
    SONIC_ROTCLASS_FULL, /* Run frame 2 */
    SONIC_ROTCLASS_FULL, /* Run frame 3 */
    SONIC_ROTCLASS_FULL, /* Run frame 4 */
    SONIC_ROTCLASS_FULL, /* Run frame 5 */
    SONIC_ROTCLASS_FULL, /* Run frame 6 */
    SONIC_ROTCLASS_FULL, /* Run frame 7 */
    SONIC_ROTCLASS_FULL, /* Run frame 8 */
    SONIC_ROTCLASS_FULL, /* Dash frame 0 */
    SONIC_ROTCLASS_FULL, /* Dash frame 1 */
    SONIC_ROTCLASS_FULL, /* Dash frame 2 */
    SONIC_ROTCLASS_FULL, /* Dash frame 3 */
    SONIC_ROTCLASS_FULL, /* Dash frame 4 */
    SONIC_ROTCLASS_NONE, /* Skid frame 0 */
    SONIC_ROTCLASS_NONE, /* Skid frame 1 */
    SONIC_ROTCLASS_NONE, /* Skid frame 2 */
    SONIC_ROTCLASS_NONE, /* Skid frame 3 */
    SONIC_ROTCLASS_NONE, /* Skid frame 4 */
    SONIC_ROTCLASS_NONE, /* Skid frame 5 */
    SONIC_ROTCLASS_NONE, /* Skid frame 6 */
    SONIC_ROTCLASS_NONE, /* Skid frame 7 */
    SONIC_ROTCLASS_NONE, /* Skid frame 8 */
    SONIC_ROTCLASS_NONE, /* Skid frame 9 */
    SONIC_ROTCLASS_NONE, /* Skid frame 10 */
    SONIC_ROTCLASS_NONE, /* Skid frame 11 */
    SONIC_ROTCLASS_NONE, /* Skid frame 12 */
    SONIC_ROTCLASS_NONE, /* Skid Turn frame 0 */
    SONIC_ROTCLASS_NONE, /* Skid Turn frame 1 */
    SONIC_ROTCLASS_NONE, /* Skid Turn frame 2 */
    SONIC_ROTCLASS_NONE, /* Skid Turn frame 3 */
    SONIC_ROTCLASS_FULL, /* Air Walk frame 0 */
    SONIC_ROTCLASS_FULL, /* Air Walk frame 1 */
    SONIC_ROTCLASS_FULL, /* Air Walk frame 2 */
    SONIC_ROTCLASS_FULL, /* Air Walk frame 3 */
    SONIC_ROTCLASS_FULL, /* Air Walk frame 4 */
    SONIC_ROTCLASS_FULL, /* Air Walk frame 5 */
    SONIC_ROTCLASS_FULL, /* Air Walk frame 6 */
    SONIC_ROTCLASS_FULL, /* Air Walk frame 7 */
    SONIC_ROTCLASS_FULL, /* Air Walk frame 8 */
    SONIC_ROTCLASS_FULL, /* Air Walk frame 9 */
    SONIC_ROTCLASS_FULL, /* Air Walk frame 10 */
    SONIC_ROTCLASS_FULL, /* Air Walk frame 11 */
    SONIC_ROTCLASS_NONE, /* Jump frame 0 */
    SONIC_ROTCLASS_NONE, /* Jump frame 1 */
    SONIC_ROTCLASS_NONE, /* Jump frame 2 */
    SONIC_ROTCLASS_NONE, /* Jump frame 3 */
    SONIC_ROTCLASS_NONE, /* Jump frame 4 */
    SONIC_ROTCLASS_NONE, /* Jump frame 5 */
    SONIC_ROTCLASS_NONE, /* Jump frame 6 */
    SONIC_ROTCLASS_NONE, /* Jump frame 7 */
    SONIC_ROTCLASS_NONE, /* Jump frame 8 */
    SONIC_ROTCLASS_NONE, /* Jump frame 9 */
    SONIC_ROTCLASS_NONE, /* Jump frame 10 */
    SONIC_ROTCLASS_NONE, /* Jump frame 11 */
    SONIC_ROTCLASS_NONE, /* Jump frame 12 */
    SONIC_ROTCLASS_NONE, /* Jump frame 13 */
    SONIC_ROTCLASS_NONE, /* Jump frame 14 */
    SONIC_ROTCLASS_NONE, /* Jump frame 15 */
    SONIC_ROTCLASS_R180, /* Push frame 0 */
    SONIC_ROTCLASS_R180, /* Push frame 1 */
    SONIC_ROTCLASS_R180, /* Push frame 2 */
    SONIC_ROTCLASS_R180, /* Push frame 3 */
    SONIC_ROTCLASS_R180, /* Push frame 4 */
    SONIC_ROTCLASS_R180, /* Push frame 5 */
    SONIC_ROTCLASS_R180, /* Push frame 6 */
    SONIC_ROTCLASS_R180, /* Push frame 7 */
    SONIC_ROTCLASS_R180, /* Push frame 8 */
    SONIC_ROTCLASS_R180, /* Push frame 9 */
    SONIC_ROTCLASS_R180, /* Look Up frame 0 */
    SONIC_ROTCLASS_R180, /* Look Up frame 1 */
    SONIC_ROTCLASS_R180, /* Look Up frame 2 */
    SONIC_ROTCLASS_R180, /* Look Up frame 3 */
    SONIC_ROTCLASS_R180, /* Look Up frame 4 */
    SONIC_ROTCLASS_R180, /* Look Up frame 5 */
    SONIC_ROTCLASS_R180, /* Look Up frame 6 */
    SONIC_ROTCLASS_R180, /* Look Up frame 7 */
    SONIC_ROTCLASS_R180, /* Crouch frame 0 */
    SONIC_ROTCLASS_R180, /* Crouch frame 1 */
    SONIC_ROTCLASS_R180, /* Crouch frame 2 */
    SONIC_ROTCLASS_R180, /* Crouch frame 3 */
    SONIC_ROTCLASS_R180, /* Crouch frame 4 */
    SONIC_ROTCLASS_R180, /* Crouch frame 5 */
};

const int16_t sonic_rot_index[SONIC_FRAME_COUNT] = {
    -1, /* Idle frame 0 */
    0, /* Walk frame 0 */
    3, /* Walk frame 1 */
    6, /* Walk frame 2 */
    9, /* Walk frame 3 */
    12, /* Walk frame 4 */
    15, /* Walk frame 5 */
    18, /* Walk frame 6 */
    21, /* Walk frame 7 */
    24, /* Walk frame 8 */
    27, /* Walk frame 9 */
    30, /* Walk frame 10 */
    33, /* Walk frame 11 */
    36, /* Jog frame 0 */
    39, /* Jog frame 1 */
    42, /* Jog frame 2 */
    45, /* Jog frame 3 */
    48, /* Jog frame 4 */
    51, /* Jog frame 5 */
    54, /* Jog frame 6 */
    57, /* Jog frame 7 */
    60, /* Jog frame 8 */
    63, /* Jog frame 9 */
    66, /* Run frame 0 */
    69, /* Run frame 1 */
    72, /* Run frame 2 */
    75, /* Run frame 3 */
    78, /* Run frame 4 */
    81, /* Run frame 5 */
    84, /* Run frame 6 */
    87, /* Run frame 7 */
    90, /* Run frame 8 */
    93, /* Dash frame 0 */
    96, /* Dash frame 1 */
    99, /* Dash frame 2 */
    102, /* Dash frame 3 */
    105, /* Dash frame 4 */
    -1, /* Skid frame 0 */
    -1, /* Skid frame 1 */
    -1, /* Skid frame 2 */
    -1, /* Skid frame 3 */
    -1, /* Skid frame 4 */
    -1, /* Skid frame 5 */
    -1, /* Skid frame 6 */
    -1, /* Skid frame 7 */
    -1, /* Skid frame 8 */
    -1, /* Skid frame 9 */
    -1, /* Skid frame 10 */
    -1, /* Skid frame 11 */
    -1, /* Skid frame 12 */
    -1, /* Skid Turn frame 0 */
    -1, /* Skid Turn frame 1 */
    -1, /* Skid Turn frame 2 */
    -1, /* Skid Turn frame 3 */
    108, /* Air Walk frame 0 */
    111, /* Air Walk frame 1 */
    114, /* Air Walk frame 2 */
    117, /* Air Walk frame 3 */
    120, /* Air Walk frame 4 */
    123, /* Air Walk frame 5 */
    126, /* Air Walk frame 6 */
    129, /* Air Walk frame 7 */
    132, /* Air Walk frame 8 */
    135, /* Air Walk frame 9 */
    138, /* Air Walk frame 10 */
    141, /* Air Walk frame 11 */
    -1, /* Jump frame 0 */
    -1, /* Jump frame 1 */
    -1, /* Jump frame 2 */
    -1, /* Jump frame 3 */
    -1, /* Jump frame 4 */
    -1, /* Jump frame 5 */
    -1, /* Jump frame 6 */
    -1, /* Jump frame 7 */
    -1, /* Jump frame 8 */
    -1, /* Jump frame 9 */
    -1, /* Jump frame 10 */
    -1, /* Jump frame 11 */
    -1, /* Jump frame 12 */
    -1, /* Jump frame 13 */
    -1, /* Jump frame 14 */
    -1, /* Jump frame 15 */
    -1, /* Push frame 0 */
    -1, /* Push frame 1 */
    -1, /* Push frame 2 */
    -1, /* Push frame 3 */
    -1, /* Push frame 4 */
    -1, /* Push frame 5 */
    -1, /* Push frame 6 */
    -1, /* Push frame 7 */
    -1, /* Push frame 8 */
    -1, /* Push frame 9 */
    -1, /* Look Up frame 0 */
    -1, /* Look Up frame 1 */
    -1, /* Look Up frame 2 */
    -1, /* Look Up frame 3 */
    -1, /* Look Up frame 4 */
    -1, /* Look Up frame 5 */
    -1, /* Look Up frame 6 */
    -1, /* Look Up frame 7 */
    -1, /* Crouch frame 0 */
    -1, /* Crouch frame 1 */
    -1, /* Crouch frame 2 */
    -1, /* Crouch frame 3 */
    -1, /* Crouch frame 4 */
    -1, /* Crouch frame 5 */
};

const SonicPiece sonic_rot_pieces[] = {
    { 8, 0, 11, 0 }, /* Walk frame 0 @ 45deg piece 0 */
    { 0, 32, 9, 12 }, /* Walk frame 0 @ 45deg piece 1 */
    { 32, 8, 6, 18 }, /* Walk frame 0 @ 45deg piece 2 */
    { 0, 0, 15, 0 }, /* Walk frame 0 @ 90deg piece 0 */
    { 32, 0, 2, 16 }, /* Walk frame 0 @ 90deg piece 1 */
    { 0, 0, 15, 0 }, /* Walk frame 0 @ 135deg piece 0 */
    { 16, 32, 5, 16 }, /* Walk frame 0 @ 135deg piece 1 */
    { 32, 16, 5, 20 }, /* Walk frame 0 @ 135deg piece 2 */
    { 32, 32, 0, 24 }, /* Walk frame 0 @ 135deg piece 3 */
    { 0, 0, 15, 0 }, /* Walk frame 1 @ 45deg piece 0 */
    { 0, 32, 9, 16 }, /* Walk frame 1 @ 45deg piece 1 */
    { 32, 8, 6, 22 }, /* Walk frame 1 @ 45deg piece 2 */
    { 0, 0, 14, 0 }, /* Walk frame 1 @ 90deg piece 0 */
    { 32, 0, 2, 12 }, /* Walk frame 1 @ 90deg piece 1 */
    { 0, 0, 15, 0 }, /* Walk frame 1 @ 135deg piece 0 */
    { 8, 32, 9, 16 }, /* Walk frame 1 @ 135deg piece 1 */
    { 32, 16, 5, 22 }, /* Walk frame 1 @ 135deg piece 2 */
    { 32, 32, 0, 26 }, /* Walk frame 1 @ 135deg piece 3 */
    { 0, 8, 14, 0 }, /* Walk frame 2 @ 45deg piece 0 */
    { 0, 32, 13, 12 }, /* Walk frame 2 @ 45deg piece 1 */
    { 32, 8, 6, 20 }, /* Walk frame 2 @ 45deg piece 2 */
    { 32, 32, 1, 26 }, /* Walk frame 2 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Walk frame 2 @ 90deg piece 0 */
    { 8, 32, 0, 16 }, /* Walk frame 2 @ 90deg piece 1 */
    { 32, 0, 3, 17 }, /* Walk frame 2 @ 90deg piece 2 */
    { 8, 0, 11, 0 }, /* Walk frame 2 @ 135deg piece 0 */
    { 8, 32, 9, 12 }, /* Walk frame 2 @ 135deg piece 1 */
    { 32, 8, 6, 18 }, /* Walk frame 2 @ 135deg piece 2 */
    { 32, 32, 5, 24 }, /* Walk frame 2 @ 135deg piece 3 */
    { 0, 8, 14, 0 }, /* Walk frame 3 @ 45deg piece 0 */
    { 16, 32, 5, 12 }, /* Walk frame 3 @ 45deg piece 1 */
    { 32, 8, 6, 16 }, /* Walk frame 3 @ 45deg piece 2 */
    { 32, 32, 1, 22 }, /* Walk frame 3 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Walk frame 3 @ 90deg piece 0 */
    { 8, 32, 0, 16 }, /* Walk frame 3 @ 90deg piece 1 */
    { 32, 8, 2, 17 }, /* Walk frame 3 @ 90deg piece 2 */
    { 8, 0, 11, 0 }, /* Walk frame 3 @ 135deg piece 0 */
    { 8, 32, 9, 12 }, /* Walk frame 3 @ 135deg piece 1 */
    { 32, 8, 6, 18 }, /* Walk frame 3 @ 135deg piece 2 */
    { 32, 32, 5, 24 }, /* Walk frame 3 @ 135deg piece 3 */
    { 0, 0, 15, 0 }, /* Walk frame 4 @ 45deg piece 0 */
    { 16, 32, 5, 16 }, /* Walk frame 4 @ 45deg piece 1 */
    { 32, 8, 6, 20 }, /* Walk frame 4 @ 45deg piece 2 */
    { 32, 32, 1, 26 }, /* Walk frame 4 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Walk frame 4 @ 90deg piece 0 */
    { 8, 32, 0, 16 }, /* Walk frame 4 @ 90deg piece 1 */
    { 32, 0, 3, 17 }, /* Walk frame 4 @ 90deg piece 2 */
    { 0, 0, 15, 0 }, /* Walk frame 4 @ 135deg piece 0 */
    { 8, 32, 9, 16 }, /* Walk frame 4 @ 135deg piece 1 */
    { 32, 8, 6, 22 }, /* Walk frame 4 @ 135deg piece 2 */
    { 32, 32, 5, 28 }, /* Walk frame 4 @ 135deg piece 3 */
    { 0, 8, 14, 0 }, /* Walk frame 5 @ 45deg piece 0 */
    { 8, 32, 9, 12 }, /* Walk frame 5 @ 45deg piece 1 */
    { 32, 8, 6, 18 }, /* Walk frame 5 @ 45deg piece 2 */
    { 32, 32, 0, 24 }, /* Walk frame 5 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Walk frame 5 @ 90deg piece 0 */
    { 32, 0, 3, 16 }, /* Walk frame 5 @ 90deg piece 1 */
    { 0, 0, 15, 0 }, /* Walk frame 5 @ 135deg piece 0 */
    { 16, 32, 5, 16 }, /* Walk frame 5 @ 135deg piece 1 */
    { 32, 16, 5, 20 }, /* Walk frame 5 @ 135deg piece 2 */
    { 32, 32, 1, 24 }, /* Walk frame 5 @ 135deg piece 3 */
    { 0, 0, 15, 0 }, /* Walk frame 6 @ 45deg piece 0 */
    { 0, 32, 8, 16 }, /* Walk frame 6 @ 45deg piece 1 */
    { 32, 8, 6, 19 }, /* Walk frame 6 @ 45deg piece 2 */
    { 0, 0, 15, 0 }, /* Walk frame 6 @ 90deg piece 0 */
    { 32, 0, 2, 16 }, /* Walk frame 6 @ 90deg piece 1 */
    { 8, 0, 11, 0 }, /* Walk frame 6 @ 135deg piece 0 */
    { 16, 32, 5, 12 }, /* Walk frame 6 @ 135deg piece 1 */
    { 32, 16, 5, 16 }, /* Walk frame 6 @ 135deg piece 2 */
    { 32, 32, 0, 20 }, /* Walk frame 6 @ 135deg piece 3 */
    { 0, 0, 15, 0 }, /* Walk frame 7 @ 45deg piece 0 */
    { 0, 32, 13, 16 }, /* Walk frame 7 @ 45deg piece 1 */
    { 32, 8, 2, 24 }, /* Walk frame 7 @ 45deg piece 2 */
    { 0, 0, 15, 0 }, /* Walk frame 7 @ 90deg piece 0 */
    { 32, 0, 2, 16 }, /* Walk frame 7 @ 90deg piece 1 */
    { 0, 0, 15, 0 }, /* Walk frame 7 @ 135deg piece 0 */
    { 16, 32, 4, 16 }, /* Walk frame 7 @ 135deg piece 1 */
    { 32, 16, 5, 18 }, /* Walk frame 7 @ 135deg piece 2 */
    { 32, 32, 0, 22 }, /* Walk frame 7 @ 135deg piece 3 */
    { 0, 8, 14, 0 }, /* Walk frame 8 @ 45deg piece 0 */
    { 0, 32, 13, 12 }, /* Walk frame 8 @ 45deg piece 1 */
    { 32, 8, 6, 20 }, /* Walk frame 8 @ 45deg piece 2 */
    { 32, 32, 1, 26 }, /* Walk frame 8 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Walk frame 8 @ 90deg piece 0 */
    { 8, 32, 0, 16 }, /* Walk frame 8 @ 90deg piece 1 */
    { 32, 0, 3, 17 }, /* Walk frame 8 @ 90deg piece 2 */
    { 0, 0, 15, 0 }, /* Walk frame 8 @ 135deg piece 0 */
    { 8, 32, 9, 16 }, /* Walk frame 8 @ 135deg piece 1 */
    { 32, 16, 5, 22 }, /* Walk frame 8 @ 135deg piece 2 */
    { 32, 32, 5, 26 }, /* Walk frame 8 @ 135deg piece 3 */
    { 0, 8, 14, 0 }, /* Walk frame 9 @ 45deg piece 0 */
    { 16, 32, 5, 12 }, /* Walk frame 9 @ 45deg piece 1 */
    { 32, 8, 6, 16 }, /* Walk frame 9 @ 45deg piece 2 */
    { 32, 32, 1, 22 }, /* Walk frame 9 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Walk frame 9 @ 90deg piece 0 */
    { 8, 32, 4, 16 }, /* Walk frame 9 @ 90deg piece 1 */
    { 32, 0, 3, 18 }, /* Walk frame 9 @ 90deg piece 2 */
    { 8, 0, 11, 0 }, /* Walk frame 9 @ 135deg piece 0 */
    { 8, 32, 9, 12 }, /* Walk frame 9 @ 135deg piece 1 */
    { 32, 8, 6, 18 }, /* Walk frame 9 @ 135deg piece 2 */
    { 32, 32, 5, 24 }, /* Walk frame 9 @ 135deg piece 3 */
    { 0, 0, 15, 0 }, /* Walk frame 10 @ 45deg piece 0 */
    { 16, 32, 5, 16 }, /* Walk frame 10 @ 45deg piece 1 */
    { 32, 0, 7, 20 }, /* Walk frame 10 @ 45deg piece 2 */
    { 32, 32, 1, 28 }, /* Walk frame 10 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Walk frame 10 @ 90deg piece 0 */
    { 8, 32, 0, 16 }, /* Walk frame 10 @ 90deg piece 1 */
    { 32, 0, 3, 17 }, /* Walk frame 10 @ 90deg piece 2 */
    { 8, 0, 11, 0 }, /* Walk frame 10 @ 135deg piece 0 */
    { 8, 32, 9, 12 }, /* Walk frame 10 @ 135deg piece 1 */
    { 32, 8, 6, 18 }, /* Walk frame 10 @ 135deg piece 2 */
    { 32, 32, 5, 24 }, /* Walk frame 10 @ 135deg piece 3 */
    { 8, 0, 11, 0 }, /* Walk frame 11 @ 45deg piece 0 */
    { 8, 32, 9, 12 }, /* Walk frame 11 @ 45deg piece 1 */
    { 32, 8, 6, 18 }, /* Walk frame 11 @ 45deg piece 2 */
    { 0, 0, 15, 0 }, /* Walk frame 11 @ 90deg piece 0 */
    { 32, 0, 2, 16 }, /* Walk frame 11 @ 90deg piece 1 */
    { 0, 8, 14, 0 }, /* Walk frame 11 @ 135deg piece 0 */
    { 16, 32, 5, 12 }, /* Walk frame 11 @ 135deg piece 1 */
    { 32, 8, 6, 16 }, /* Walk frame 11 @ 135deg piece 2 */
    { 32, 32, 5, 22 }, /* Walk frame 11 @ 135deg piece 3 */
    { 0, 8, 14, 0 }, /* Jog frame 0 @ 45deg piece 0 */
    { 16, 32, 5, 12 }, /* Jog frame 0 @ 45deg piece 1 */
    { 32, 8, 6, 16 }, /* Jog frame 0 @ 45deg piece 2 */
    { 32, 32, 0, 22 }, /* Jog frame 0 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Jog frame 0 @ 90deg piece 0 */
    { 8, 32, 4, 16 }, /* Jog frame 0 @ 90deg piece 1 */
    { 32, 8, 2, 18 }, /* Jog frame 0 @ 90deg piece 2 */
    { 0, 0, 15, 0 }, /* Jog frame 0 @ 135deg piece 0 */
    { 8, 32, 9, 16 }, /* Jog frame 0 @ 135deg piece 1 */
    { 32, 8, 6, 22 }, /* Jog frame 0 @ 135deg piece 2 */
    { 32, 32, 5, 28 }, /* Jog frame 0 @ 135deg piece 3 */
    { 8, 8, 10, 0 }, /* Jog frame 1 @ 45deg piece 0 */
    { 8, 32, 9, 9 }, /* Jog frame 1 @ 45deg piece 1 */
    { 32, 8, 6, 15 }, /* Jog frame 1 @ 45deg piece 2 */
    { 32, 32, 0, 21 }, /* Jog frame 1 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Jog frame 1 @ 90deg piece 0 */
    { 32, 8, 2, 16 }, /* Jog frame 1 @ 90deg piece 1 */
    { 0, 8, 14, 0 }, /* Jog frame 1 @ 135deg piece 0 */
    { 8, 32, 9, 12 }, /* Jog frame 1 @ 135deg piece 1 */
    { 32, 8, 6, 18 }, /* Jog frame 1 @ 135deg piece 2 */
    { 32, 32, 1, 24 }, /* Jog frame 1 @ 135deg piece 3 */
    { 0, 0, 15, 0 }, /* Jog frame 2 @ 45deg piece 0 */
    { 0, 32, 8, 16 }, /* Jog frame 2 @ 45deg piece 1 */
    { 32, 8, 6, 19 }, /* Jog frame 2 @ 45deg piece 2 */
    { 0, 0, 15, 0 }, /* Jog frame 2 @ 90deg piece 0 */
    { 32, 0, 3, 16 }, /* Jog frame 2 @ 90deg piece 1 */
    { 8, 0, 11, 0 }, /* Jog frame 2 @ 135deg piece 0 */
    { 8, 32, 9, 12 }, /* Jog frame 2 @ 135deg piece 1 */
    { 32, 16, 5, 18 }, /* Jog frame 2 @ 135deg piece 2 */
    { 32, 32, 0, 22 }, /* Jog frame 2 @ 135deg piece 3 */
    { 0, 8, 14, 0 }, /* Jog frame 3 @ 45deg piece 0 */
    { 0, 32, 13, 12 }, /* Jog frame 3 @ 45deg piece 1 */
    { 32, 8, 6, 20 }, /* Jog frame 3 @ 45deg piece 2 */
    { 32, 32, 0, 26 }, /* Jog frame 3 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Jog frame 3 @ 90deg piece 0 */
    { 32, 8, 2, 16 }, /* Jog frame 3 @ 90deg piece 1 */
    { 0, 0, 15, 0 }, /* Jog frame 3 @ 135deg piece 0 */
    { 16, 32, 5, 16 }, /* Jog frame 3 @ 135deg piece 1 */
    { 32, 16, 5, 20 }, /* Jog frame 3 @ 135deg piece 2 */
    { 32, 32, 1, 24 }, /* Jog frame 3 @ 135deg piece 3 */
    { 0, 8, 14, 0 }, /* Jog frame 4 @ 45deg piece 0 */
    { 0, 32, 13, 12 }, /* Jog frame 4 @ 45deg piece 1 */
    { 32, 8, 6, 20 }, /* Jog frame 4 @ 45deg piece 2 */
    { 32, 32, 1, 26 }, /* Jog frame 4 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Jog frame 4 @ 90deg piece 0 */
    { 8, 32, 0, 16 }, /* Jog frame 4 @ 90deg piece 1 */
    { 32, 8, 2, 17 }, /* Jog frame 4 @ 90deg piece 2 */
    { 0, 0, 15, 0 }, /* Jog frame 4 @ 135deg piece 0 */
    { 8, 32, 9, 16 }, /* Jog frame 4 @ 135deg piece 1 */
    { 32, 16, 5, 22 }, /* Jog frame 4 @ 135deg piece 2 */
    { 32, 32, 1, 26 }, /* Jog frame 4 @ 135deg piece 3 */
    { 0, 8, 14, 0 }, /* Jog frame 5 @ 45deg piece 0 */
    { 16, 32, 5, 12 }, /* Jog frame 5 @ 45deg piece 1 */
    { 32, 8, 6, 16 }, /* Jog frame 5 @ 45deg piece 2 */
    { 32, 32, 0, 22 }, /* Jog frame 5 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Jog frame 5 @ 90deg piece 0 */
    { 32, 8, 2, 16 }, /* Jog frame 5 @ 90deg piece 1 */
    { 0, 0, 15, 0 }, /* Jog frame 5 @ 135deg piece 0 */
    { 8, 32, 9, 16 }, /* Jog frame 5 @ 135deg piece 1 */
    { 32, 8, 6, 22 }, /* Jog frame 5 @ 135deg piece 2 */
    { 32, 32, 5, 28 }, /* Jog frame 5 @ 135deg piece 3 */
    { 8, 0, 11, 0 }, /* Jog frame 6 @ 45deg piece 0 */
    { 8, 32, 9, 12 }, /* Jog frame 6 @ 45deg piece 1 */
    { 32, 8, 6, 18 }, /* Jog frame 6 @ 45deg piece 2 */
    { 0, 0, 15, 0 }, /* Jog frame 6 @ 90deg piece 0 */
    { 32, 0, 3, 16 }, /* Jog frame 6 @ 90deg piece 1 */
    { 0, 8, 14, 0 }, /* Jog frame 6 @ 135deg piece 0 */
    { 16, 32, 5, 12 }, /* Jog frame 6 @ 135deg piece 1 */
    { 32, 16, 5, 16 }, /* Jog frame 6 @ 135deg piece 2 */
    { 32, 32, 0, 20 }, /* Jog frame 6 @ 135deg piece 3 */
    { 0, 0, 15, 0 }, /* Jog frame 7 @ 45deg piece 0 */
    { 0, 32, 13, 16 }, /* Jog frame 7 @ 45deg piece 1 */
    { 32, 8, 6, 24 }, /* Jog frame 7 @ 45deg piece 2 */
    { 0, 0, 15, 0 }, /* Jog frame 7 @ 90deg piece 0 */
    { 32, 0, 2, 16 }, /* Jog frame 7 @ 90deg piece 1 */
    { 0, 0, 15, 0 }, /* Jog frame 7 @ 135deg piece 0 */
    { 16, 32, 5, 16 }, /* Jog frame 7 @ 135deg piece 1 */
    { 32, 16, 5, 20 }, /* Jog frame 7 @ 135deg piece 2 */
    { 32, 32, 0, 24 }, /* Jog frame 7 @ 135deg piece 3 */
    { 0, 8, 14, 0 }, /* Jog frame 8 @ 45deg piece 0 */
    { 0, 32, 12, 12 }, /* Jog frame 8 @ 45deg piece 1 */
    { 32, 8, 6, 16 }, /* Jog frame 8 @ 45deg piece 2 */
    { 32, 32, 0, 22 }, /* Jog frame 8 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Jog frame 8 @ 90deg piece 0 */
    { 32, 0, 3, 16 }, /* Jog frame 8 @ 90deg piece 1 */
    { 8, 0, 11, 0 }, /* Jog frame 8 @ 135deg piece 0 */
    { 8, 32, 9, 12 }, /* Jog frame 8 @ 135deg piece 1 */
    { 32, 16, 5, 18 }, /* Jog frame 8 @ 135deg piece 2 */
    { 32, 32, 5, 22 }, /* Jog frame 8 @ 135deg piece 3 */
    { 0, 8, 14, 0 }, /* Jog frame 9 @ 45deg piece 0 */
    { 0, 32, 13, 12 }, /* Jog frame 9 @ 45deg piece 1 */
    { 32, 8, 6, 20 }, /* Jog frame 9 @ 45deg piece 2 */
    { 32, 32, 0, 26 }, /* Jog frame 9 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Jog frame 9 @ 90deg piece 0 */
    { 32, 8, 2, 16 }, /* Jog frame 9 @ 90deg piece 1 */
    { 8, 0, 11, 0 }, /* Jog frame 9 @ 135deg piece 0 */
    { 16, 32, 5, 12 }, /* Jog frame 9 @ 135deg piece 1 */
    { 32, 8, 6, 16 }, /* Jog frame 9 @ 135deg piece 2 */
    { 32, 32, 1, 22 }, /* Jog frame 9 @ 135deg piece 3 */
    { 0, 8, 14, 0 }, /* Run frame 0 @ 45deg piece 0 */
    { 8, 32, 9, 12 }, /* Run frame 0 @ 45deg piece 1 */
    { 32, 8, 6, 18 }, /* Run frame 0 @ 45deg piece 2 */
    { 32, 32, 4, 24 }, /* Run frame 0 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Run frame 0 @ 90deg piece 0 */
    { 16, 32, 4, 16 }, /* Run frame 0 @ 90deg piece 1 */
    { 32, 8, 2, 18 }, /* Run frame 0 @ 90deg piece 2 */
    { 8, 0, 11, 0 }, /* Run frame 0 @ 135deg piece 0 */
    { 8, 32, 9, 12 }, /* Run frame 0 @ 135deg piece 1 */
    { 32, 8, 2, 18 }, /* Run frame 0 @ 135deg piece 2 */
    { 32, 32, 1, 21 }, /* Run frame 0 @ 135deg piece 3 */
    { 0, 8, 14, 0 }, /* Run frame 1 @ 45deg piece 0 */
    { 0, 32, 13, 12 }, /* Run frame 1 @ 45deg piece 1 */
    { 32, 8, 6, 20 }, /* Run frame 1 @ 45deg piece 2 */
    { 32, 32, 0, 26 }, /* Run frame 1 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Run frame 1 @ 90deg piece 0 */
    { 32, 8, 2, 16 }, /* Run frame 1 @ 90deg piece 1 */
    { 0, 0, 15, 0 }, /* Run frame 1 @ 135deg piece 0 */
    { 8, 32, 9, 16 }, /* Run frame 1 @ 135deg piece 1 */
    { 32, 16, 1, 22 }, /* Run frame 1 @ 135deg piece 2 */
    { 32, 32, 0, 24 }, /* Run frame 1 @ 135deg piece 3 */
    { 0, 8, 14, 0 }, /* Run frame 2 @ 45deg piece 0 */
    { 8, 32, 9, 12 }, /* Run frame 2 @ 45deg piece 1 */
    { 32, 8, 6, 18 }, /* Run frame 2 @ 45deg piece 2 */
    { 32, 32, 0, 24 }, /* Run frame 2 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Run frame 2 @ 90deg piece 0 */
    { 32, 8, 2, 16 }, /* Run frame 2 @ 90deg piece 1 */
    { 0, 0, 15, 0 }, /* Run frame 2 @ 135deg piece 0 */
    { 8, 32, 9, 16 }, /* Run frame 2 @ 135deg piece 1 */
    { 32, 16, 1, 22 }, /* Run frame 2 @ 135deg piece 2 */
    { 32, 32, 0, 24 }, /* Run frame 2 @ 135deg piece 3 */
    { 0, 8, 14, 0 }, /* Run frame 3 @ 45deg piece 0 */
    { 0, 32, 13, 12 }, /* Run frame 3 @ 45deg piece 1 */
    { 32, 8, 6, 20 }, /* Run frame 3 @ 45deg piece 2 */
    { 32, 32, 0, 26 }, /* Run frame 3 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Run frame 3 @ 90deg piece 0 */
    { 32, 8, 2, 16 }, /* Run frame 3 @ 90deg piece 1 */
    { 0, 0, 15, 0 }, /* Run frame 3 @ 135deg piece 0 */
    { 8, 32, 9, 16 }, /* Run frame 3 @ 135deg piece 1 */
    { 32, 16, 1, 22 }, /* Run frame 3 @ 135deg piece 2 */
    { 32, 32, 0, 24 }, /* Run frame 3 @ 135deg piece 3 */
    { 0, 8, 14, 0 }, /* Run frame 4 @ 45deg piece 0 */
    { 0, 32, 13, 12 }, /* Run frame 4 @ 45deg piece 1 */
    { 32, 8, 6, 20 }, /* Run frame 4 @ 45deg piece 2 */
    { 32, 32, 0, 26 }, /* Run frame 4 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Run frame 4 @ 90deg piece 0 */
    { 32, 0, 3, 16 }, /* Run frame 4 @ 90deg piece 1 */
    { 0, 0, 15, 0 }, /* Run frame 4 @ 135deg piece 0 */
    { 8, 32, 9, 16 }, /* Run frame 4 @ 135deg piece 1 */
    { 32, 16, 1, 22 }, /* Run frame 4 @ 135deg piece 2 */
    { 32, 32, 0, 24 }, /* Run frame 4 @ 135deg piece 3 */
    { 0, 8, 14, 0 }, /* Run frame 5 @ 45deg piece 0 */
    { 0, 32, 13, 12 }, /* Run frame 5 @ 45deg piece 1 */
    { 32, 8, 6, 20 }, /* Run frame 5 @ 45deg piece 2 */
    { 32, 32, 0, 26 }, /* Run frame 5 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Run frame 5 @ 90deg piece 0 */
    { 32, 0, 3, 16 }, /* Run frame 5 @ 90deg piece 1 */
    { 0, 0, 15, 0 }, /* Run frame 5 @ 135deg piece 0 */
    { 8, 32, 9, 16 }, /* Run frame 5 @ 135deg piece 1 */
    { 32, 16, 1, 22 }, /* Run frame 5 @ 135deg piece 2 */
    { 32, 32, 0, 24 }, /* Run frame 5 @ 135deg piece 3 */
    { 0, 8, 14, 0 }, /* Run frame 6 @ 45deg piece 0 */
    { 0, 32, 13, 12 }, /* Run frame 6 @ 45deg piece 1 */
    { 32, 8, 6, 20 }, /* Run frame 6 @ 45deg piece 2 */
    { 32, 32, 0, 26 }, /* Run frame 6 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Run frame 6 @ 90deg piece 0 */
    { 32, 8, 2, 16 }, /* Run frame 6 @ 90deg piece 1 */
    { 0, 0, 15, 0 }, /* Run frame 6 @ 135deg piece 0 */
    { 8, 32, 9, 16 }, /* Run frame 6 @ 135deg piece 1 */
    { 32, 16, 1, 22 }, /* Run frame 6 @ 135deg piece 2 */
    { 32, 32, 0, 24 }, /* Run frame 6 @ 135deg piece 3 */
    { 0, 8, 14, 0 }, /* Run frame 7 @ 45deg piece 0 */
    { 0, 32, 13, 12 }, /* Run frame 7 @ 45deg piece 1 */
    { 32, 8, 6, 20 }, /* Run frame 7 @ 45deg piece 2 */
    { 32, 32, 0, 26 }, /* Run frame 7 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Run frame 7 @ 90deg piece 0 */
    { 32, 8, 2, 16 }, /* Run frame 7 @ 90deg piece 1 */
    { 0, 0, 15, 0 }, /* Run frame 7 @ 135deg piece 0 */
    { 8, 32, 9, 16 }, /* Run frame 7 @ 135deg piece 1 */
    { 32, 16, 1, 22 }, /* Run frame 7 @ 135deg piece 2 */
    { 32, 32, 0, 24 }, /* Run frame 7 @ 135deg piece 3 */
    { 0, 8, 14, 0 }, /* Run frame 8 @ 45deg piece 0 */
    { 0, 32, 13, 12 }, /* Run frame 8 @ 45deg piece 1 */
    { 32, 8, 6, 20 }, /* Run frame 8 @ 45deg piece 2 */
    { 32, 32, 0, 26 }, /* Run frame 8 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Run frame 8 @ 90deg piece 0 */
    { 32, 0, 3, 16 }, /* Run frame 8 @ 90deg piece 1 */
    { 0, 0, 15, 0 }, /* Run frame 8 @ 135deg piece 0 */
    { 8, 32, 9, 16 }, /* Run frame 8 @ 135deg piece 1 */
    { 32, 16, 1, 22 }, /* Run frame 8 @ 135deg piece 2 */
    { 32, 32, 0, 24 }, /* Run frame 8 @ 135deg piece 3 */
    { 0, 8, 14, 0 }, /* Dash frame 0 @ 45deg piece 0 */
    { 8, 32, 9, 12 }, /* Dash frame 0 @ 45deg piece 1 */
    { 32, 8, 6, 18 }, /* Dash frame 0 @ 45deg piece 2 */
    { 32, 32, 4, 24 }, /* Dash frame 0 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Dash frame 0 @ 90deg piece 0 */
    { 16, 32, 4, 16 }, /* Dash frame 0 @ 90deg piece 1 */
    { 32, 8, 2, 18 }, /* Dash frame 0 @ 90deg piece 2 */
    { 8, 0, 11, 0 }, /* Dash frame 0 @ 135deg piece 0 */
    { 8, 32, 9, 12 }, /* Dash frame 0 @ 135deg piece 1 */
    { 32, 8, 2, 18 }, /* Dash frame 0 @ 135deg piece 2 */
    { 32, 32, 1, 21 }, /* Dash frame 0 @ 135deg piece 3 */
    { 0, 0, 15, 0 }, /* Dash frame 1 @ 45deg piece 0 */
    { 8, 32, 9, 16 }, /* Dash frame 1 @ 45deg piece 1 */
    { 32, 8, 6, 22 }, /* Dash frame 1 @ 45deg piece 2 */
    { 32, 32, 4, 28 }, /* Dash frame 1 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Dash frame 1 @ 90deg piece 0 */
    { 8, 32, 8, 16 }, /* Dash frame 1 @ 90deg piece 1 */
    { 8, 0, 11, 0 }, /* Dash frame 1 @ 135deg piece 0 */
    { 8, 32, 9, 12 }, /* Dash frame 1 @ 135deg piece 1 */
    { 32, 0, 7, 18 }, /* Dash frame 1 @ 135deg piece 2 */
    { 32, 32, 0, 26 }, /* Dash frame 1 @ 135deg piece 3 */
    { 0, 0, 15, 0 }, /* Dash frame 2 @ 45deg piece 0 */
    { 8, 32, 9, 16 }, /* Dash frame 2 @ 45deg piece 1 */
    { 32, 8, 6, 22 }, /* Dash frame 2 @ 45deg piece 2 */
    { 32, 32, 4, 28 }, /* Dash frame 2 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Dash frame 2 @ 90deg piece 0 */
    { 8, 32, 8, 16 }, /* Dash frame 2 @ 90deg piece 1 */
    { 32, 16, 1, 19 }, /* Dash frame 2 @ 90deg piece 2 */
    { 8, 0, 11, 0 }, /* Dash frame 2 @ 135deg piece 0 */
    { 8, 32, 9, 12 }, /* Dash frame 2 @ 135deg piece 1 */
    { 32, 0, 7, 18 }, /* Dash frame 2 @ 135deg piece 2 */
    { 32, 32, 1, 26 }, /* Dash frame 2 @ 135deg piece 3 */
    { 0, 0, 15, 0 }, /* Dash frame 3 @ 45deg piece 0 */
    { 8, 32, 9, 16 }, /* Dash frame 3 @ 45deg piece 1 */
    { 32, 8, 6, 22 }, /* Dash frame 3 @ 45deg piece 2 */
    { 32, 32, 4, 28 }, /* Dash frame 3 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Dash frame 3 @ 90deg piece 0 */
    { 8, 32, 8, 16 }, /* Dash frame 3 @ 90deg piece 1 */
    { 8, 0, 11, 0 }, /* Dash frame 3 @ 135deg piece 0 */
    { 8, 32, 9, 12 }, /* Dash frame 3 @ 135deg piece 1 */
    { 32, 8, 6, 18 }, /* Dash frame 3 @ 135deg piece 2 */
    { 32, 32, 0, 24 }, /* Dash frame 3 @ 135deg piece 3 */
    { 0, 0, 15, 0 }, /* Dash frame 4 @ 45deg piece 0 */
    { 8, 32, 9, 16 }, /* Dash frame 4 @ 45deg piece 1 */
    { 32, 8, 6, 22 }, /* Dash frame 4 @ 45deg piece 2 */
    { 32, 32, 4, 28 }, /* Dash frame 4 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Dash frame 4 @ 90deg piece 0 */
    { 8, 32, 8, 16 }, /* Dash frame 4 @ 90deg piece 1 */
    { 32, 16, 1, 19 }, /* Dash frame 4 @ 90deg piece 2 */
    { 8, 0, 11, 0 }, /* Dash frame 4 @ 135deg piece 0 */
    { 8, 32, 9, 12 }, /* Dash frame 4 @ 135deg piece 1 */
    { 32, 0, 7, 18 }, /* Dash frame 4 @ 135deg piece 2 */
    { 32, 32, 1, 26 }, /* Dash frame 4 @ 135deg piece 3 */
    { 8, 0, 11, 0 }, /* Air Walk frame 0 @ 45deg piece 0 */
    { 8, 32, 5, 12 }, /* Air Walk frame 0 @ 45deg piece 1 */
    { 32, 0, 7, 16 }, /* Air Walk frame 0 @ 45deg piece 2 */
    { 0, 0, 15, 0 }, /* Air Walk frame 0 @ 90deg piece 0 */
    { 32, 0, 6, 16 }, /* Air Walk frame 0 @ 90deg piece 1 */
    { 0, 8, 14, 0 }, /* Air Walk frame 0 @ 135deg piece 0 */
    { 16, 32, 5, 12 }, /* Air Walk frame 0 @ 135deg piece 1 */
    { 32, 16, 5, 16 }, /* Air Walk frame 0 @ 135deg piece 2 */
    { 32, 32, 5, 20 }, /* Air Walk frame 0 @ 135deg piece 3 */
    { 0, 0, 15, 0 }, /* Air Walk frame 1 @ 45deg piece 0 */
    { 0, 32, 8, 16 }, /* Air Walk frame 1 @ 45deg piece 1 */
    { 32, 0, 7, 19 }, /* Air Walk frame 1 @ 45deg piece 2 */
    { 0, 0, 14, 0 }, /* Air Walk frame 1 @ 90deg piece 0 */
    { 32, 0, 6, 12 }, /* Air Walk frame 1 @ 90deg piece 1 */
    { 8, 0, 11, 0 }, /* Air Walk frame 1 @ 135deg piece 0 */
    { 16, 32, 5, 12 }, /* Air Walk frame 1 @ 135deg piece 1 */
    { 32, 16, 5, 16 }, /* Air Walk frame 1 @ 135deg piece 2 */
    { 32, 32, 5, 20 }, /* Air Walk frame 1 @ 135deg piece 3 */
    { 0, 8, 14, 0 }, /* Air Walk frame 2 @ 45deg piece 0 */
    { 0, 32, 13, 12 }, /* Air Walk frame 2 @ 45deg piece 1 */
    { 32, 0, 7, 20 }, /* Air Walk frame 2 @ 45deg piece 2 */
    { 32, 32, 1, 28 }, /* Air Walk frame 2 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Air Walk frame 2 @ 90deg piece 0 */
    { 8, 32, 4, 16 }, /* Air Walk frame 2 @ 90deg piece 1 */
    { 32, 0, 7, 18 }, /* Air Walk frame 2 @ 90deg piece 2 */
    { 8, 0, 11, 0 }, /* Air Walk frame 2 @ 135deg piece 0 */
    { 8, 32, 9, 12 }, /* Air Walk frame 2 @ 135deg piece 1 */
    { 32, 8, 6, 18 }, /* Air Walk frame 2 @ 135deg piece 2 */
    { 32, 32, 9, 24 }, /* Air Walk frame 2 @ 135deg piece 3 */
    { 0, 8, 14, 0 }, /* Air Walk frame 3 @ 45deg piece 0 */
    { 16, 32, 5, 12 }, /* Air Walk frame 3 @ 45deg piece 1 */
    { 32, 8, 6, 16 }, /* Air Walk frame 3 @ 45deg piece 2 */
    { 32, 32, 1, 22 }, /* Air Walk frame 3 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Air Walk frame 3 @ 90deg piece 0 */
    { 8, 32, 4, 16 }, /* Air Walk frame 3 @ 90deg piece 1 */
    { 32, 8, 6, 18 }, /* Air Walk frame 3 @ 90deg piece 2 */
    { 8, 0, 11, 0 }, /* Air Walk frame 3 @ 135deg piece 0 */
    { 8, 32, 9, 12 }, /* Air Walk frame 3 @ 135deg piece 1 */
    { 32, 8, 6, 18 }, /* Air Walk frame 3 @ 135deg piece 2 */
    { 32, 32, 5, 24 }, /* Air Walk frame 3 @ 135deg piece 3 */
    { 0, 8, 14, 0 }, /* Air Walk frame 4 @ 45deg piece 0 */
    { 16, 32, 5, 12 }, /* Air Walk frame 4 @ 45deg piece 1 */
    { 32, 0, 7, 16 }, /* Air Walk frame 4 @ 45deg piece 2 */
    { 32, 32, 1, 24 }, /* Air Walk frame 4 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Air Walk frame 4 @ 90deg piece 0 */
    { 8, 32, 0, 16 }, /* Air Walk frame 4 @ 90deg piece 1 */
    { 32, 0, 7, 17 }, /* Air Walk frame 4 @ 90deg piece 2 */
    { 8, 0, 11, 0 }, /* Air Walk frame 4 @ 135deg piece 0 */
    { 8, 32, 9, 12 }, /* Air Walk frame 4 @ 135deg piece 1 */
    { 32, 8, 6, 18 }, /* Air Walk frame 4 @ 135deg piece 2 */
    { 32, 32, 5, 24 }, /* Air Walk frame 4 @ 135deg piece 3 */
    { 0, 8, 14, 0 }, /* Air Walk frame 5 @ 45deg piece 0 */
    { 8, 32, 9, 12 }, /* Air Walk frame 5 @ 45deg piece 1 */
    { 32, 0, 7, 18 }, /* Air Walk frame 5 @ 45deg piece 2 */
    { 0, 0, 15, 0 }, /* Air Walk frame 5 @ 90deg piece 0 */
    { 32, 0, 7, 16 }, /* Air Walk frame 5 @ 90deg piece 1 */
    { 0, 0, 15, 0 }, /* Air Walk frame 5 @ 135deg piece 0 */
    { 16, 32, 5, 16 }, /* Air Walk frame 5 @ 135deg piece 1 */
    { 32, 8, 2, 20 }, /* Air Walk frame 5 @ 135deg piece 2 */
    { 32, 32, 5, 23 }, /* Air Walk frame 5 @ 135deg piece 3 */
    { 0, 0, 15, 0 }, /* Air Walk frame 6 @ 45deg piece 0 */
    { 0, 32, 8, 16 }, /* Air Walk frame 6 @ 45deg piece 1 */
    { 32, 0, 7, 19 }, /* Air Walk frame 6 @ 45deg piece 2 */
    { 0, 0, 15, 0 }, /* Air Walk frame 6 @ 90deg piece 0 */
    { 32, 0, 6, 16 }, /* Air Walk frame 6 @ 90deg piece 1 */
    { 8, 0, 11, 0 }, /* Air Walk frame 6 @ 135deg piece 0 */
    { 16, 32, 5, 12 }, /* Air Walk frame 6 @ 135deg piece 1 */
    { 32, 16, 5, 16 }, /* Air Walk frame 6 @ 135deg piece 2 */
    { 32, 32, 5, 20 }, /* Air Walk frame 6 @ 135deg piece 3 */
    { 0, 0, 15, 0 }, /* Air Walk frame 7 @ 45deg piece 0 */
    { 0, 32, 13, 16 }, /* Air Walk frame 7 @ 45deg piece 1 */
    { 32, 0, 7, 24 }, /* Air Walk frame 7 @ 45deg piece 2 */
    { 0, 0, 15, 0 }, /* Air Walk frame 7 @ 90deg piece 0 */
    { 32, 0, 7, 16 }, /* Air Walk frame 7 @ 90deg piece 1 */
    { 0, 0, 15, 0 }, /* Air Walk frame 7 @ 135deg piece 0 */
    { 16, 32, 5, 16 }, /* Air Walk frame 7 @ 135deg piece 1 */
    { 32, 16, 5, 20 }, /* Air Walk frame 7 @ 135deg piece 2 */
    { 32, 32, 5, 24 }, /* Air Walk frame 7 @ 135deg piece 3 */
    { 0, 8, 14, 0 }, /* Air Walk frame 8 @ 45deg piece 0 */
    { 16, 32, 5, 12 }, /* Air Walk frame 8 @ 45deg piece 1 */
    { 32, 0, 7, 16 }, /* Air Walk frame 8 @ 45deg piece 2 */
    { 32, 32, 1, 24 }, /* Air Walk frame 8 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Air Walk frame 8 @ 90deg piece 0 */
    { 8, 32, 0, 16 }, /* Air Walk frame 8 @ 90deg piece 1 */
    { 32, 0, 7, 17 }, /* Air Walk frame 8 @ 90deg piece 2 */
    { 8, 0, 11, 0 }, /* Air Walk frame 8 @ 135deg piece 0 */
    { 8, 32, 9, 12 }, /* Air Walk frame 8 @ 135deg piece 1 */
    { 32, 8, 6, 18 }, /* Air Walk frame 8 @ 135deg piece 2 */
    { 32, 32, 9, 24 }, /* Air Walk frame 8 @ 135deg piece 3 */
    { 0, 8, 14, 0 }, /* Air Walk frame 9 @ 45deg piece 0 */
    { 24, 32, 1, 12 }, /* Air Walk frame 9 @ 45deg piece 1 */
    { 32, 0, 7, 14 }, /* Air Walk frame 9 @ 45deg piece 2 */
    { 32, 32, 1, 22 }, /* Air Walk frame 9 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Air Walk frame 9 @ 90deg piece 0 */
    { 8, 32, 4, 16 }, /* Air Walk frame 9 @ 90deg piece 1 */
    { 32, 0, 7, 18 }, /* Air Walk frame 9 @ 90deg piece 2 */
    { 8, 0, 11, 0 }, /* Air Walk frame 9 @ 135deg piece 0 */
    { 8, 32, 9, 12 }, /* Air Walk frame 9 @ 135deg piece 1 */
    { 32, 0, 7, 18 }, /* Air Walk frame 9 @ 135deg piece 2 */
    { 32, 32, 9, 26 }, /* Air Walk frame 9 @ 135deg piece 3 */
    { 0, 0, 15, 0 }, /* Air Walk frame 10 @ 45deg piece 0 */
    { 16, 32, 5, 16 }, /* Air Walk frame 10 @ 45deg piece 1 */
    { 32, 0, 7, 20 }, /* Air Walk frame 10 @ 45deg piece 2 */
    { 32, 32, 1, 28 }, /* Air Walk frame 10 @ 45deg piece 3 */
    { 0, 0, 15, 0 }, /* Air Walk frame 10 @ 90deg piece 0 */
    { 8, 32, 4, 16 }, /* Air Walk frame 10 @ 90deg piece 1 */
    { 32, 0, 7, 18 }, /* Air Walk frame 10 @ 90deg piece 2 */
    { 8, 0, 11, 0 }, /* Air Walk frame 10 @ 135deg piece 0 */
    { 8, 32, 9, 12 }, /* Air Walk frame 10 @ 135deg piece 1 */
    { 32, 8, 10, 18 }, /* Air Walk frame 10 @ 135deg piece 2 */
    { 32, 32, 9, 27 }, /* Air Walk frame 10 @ 135deg piece 3 */
    { 8, 0, 11, 0 }, /* Air Walk frame 11 @ 45deg piece 0 */
    { 16, 32, 5, 12 }, /* Air Walk frame 11 @ 45deg piece 1 */
    { 32, 0, 7, 16 }, /* Air Walk frame 11 @ 45deg piece 2 */
    { 0, 0, 15, 0 }, /* Air Walk frame 11 @ 90deg piece 0 */
    { 32, 0, 7, 16 }, /* Air Walk frame 11 @ 90deg piece 1 */
    { 8, 8, 10, 0 }, /* Air Walk frame 11 @ 135deg piece 0 */
    { 16, 32, 5, 9 }, /* Air Walk frame 11 @ 135deg piece 1 */
    { 32, 8, 10, 13 }, /* Air Walk frame 11 @ 135deg piece 2 */
    { 32, 32, 9, 22 }, /* Air Walk frame 11 @ 135deg piece 3 */
};

const SonicRotFrame sonic_rot_frames[] = {
    { 0, 0, 24, 3, -24, -24 }, /* Walk frame 0 @ 45deg */
    { 24, 3, 19, 2, -20, -13 }, /* Walk frame 0 @ 90deg */
    { 43, 5, 25, 4, -23, -24 }, /* Walk frame 0 @ 135deg */
    { 68, 9, 28, 3, -24, -24 }, /* Walk frame 1 @ 45deg */
    { 96, 12, 15, 2, -20, -13 }, /* Walk frame 1 @ 90deg */
    { 111, 14, 27, 4, -22, -24 }, /* Walk frame 1 @ 135deg */
    { 138, 18, 28, 4, -27, -27 }, /* Walk frame 2 @ 45deg */
    { 166, 22, 21, 3, -20, -18 }, /* Walk frame 2 @ 90deg */
    { 187, 25, 28, 4, -27, -27 }, /* Walk frame 2 @ 135deg */
    { 215, 29, 24, 4, -28, -28 }, /* Walk frame 3 @ 45deg */
    { 239, 33, 20, 3, -20, -19 }, /* Walk frame 3 @ 90deg */
    { 259, 36, 28, 4, -27, -28 }, /* Walk frame 3 @ 135deg */
    { 287, 40, 28, 4, -27, -27 }, /* Walk frame 4 @ 45deg */
    { 315, 44, 21, 3, -20, -18 }, /* Walk frame 4 @ 90deg */
    { 336, 47, 32, 4, -25, -27 }, /* Walk frame 4 @ 135deg */
    { 368, 51, 25, 4, -27, -27 }, /* Walk frame 5 @ 45deg */
    { 393, 55, 20, 2, -20, -18 }, /* Walk frame 5 @ 90deg */
    { 413, 57, 26, 4, -22, -27 }, /* Walk frame 5 @ 135deg */
    { 439, 61, 25, 3, -24, -24 }, /* Walk frame 6 @ 45deg */
    { 464, 64, 19, 2, -20, -13 }, /* Walk frame 6 @ 90deg */
    { 483, 66, 21, 4, -23, -24 }, /* Walk frame 6 @ 135deg */
    { 504, 70, 27, 3, -25, -25 }, /* Walk frame 7 @ 45deg */
    { 531, 73, 19, 2, -20, -14 }, /* Walk frame 7 @ 90deg */
    { 550, 75, 23, 4, -23, -25 }, /* Walk frame 7 @ 135deg */
    { 573, 79, 28, 4, -27, -27 }, /* Walk frame 8 @ 45deg */
    { 601, 83, 21, 3, -20, -17 }, /* Walk frame 8 @ 90deg */
    { 622, 86, 30, 4, -27, -27 }, /* Walk frame 8 @ 135deg */
    { 652, 90, 24, 4, -27, -27 }, /* Walk frame 9 @ 45deg */
    { 676, 94, 22, 3, -20, -18 }, /* Walk frame 9 @ 90deg */
    { 698, 97, 28, 4, -28, -27 }, /* Walk frame 9 @ 135deg */
    { 726, 101, 30, 4, -25, -25 }, /* Walk frame 10 @ 45deg */
    { 756, 105, 21, 3, -20, -15 }, /* Walk frame 10 @ 90deg */
    { 777, 108, 28, 4, -28, -25 }, /* Walk frame 10 @ 135deg */
    { 805, 112, 24, 3, -25, -25 }, /* Walk frame 11 @ 45deg */
    { 829, 115, 19, 2, -20, -14 }, /* Walk frame 11 @ 90deg */
    { 848, 117, 26, 4, -27, -25 }, /* Walk frame 11 @ 135deg */
    { 874, 121, 23, 4, -28, -26 }, /* Jog frame 0 @ 45deg */
    { 897, 125, 21, 3, -20, -19 }, /* Jog frame 0 @ 90deg */
    { 918, 128, 32, 4, -25, -28 }, /* Jog frame 0 @ 135deg */
    { 950, 132, 22, 4, -27, -25 }, /* Jog frame 1 @ 45deg */
    { 972, 136, 19, 2, -20, -18 }, /* Jog frame 1 @ 90deg */
    { 991, 138, 26, 4, -24, -27 }, /* Jog frame 1 @ 135deg */
    { 1017, 142, 25, 3, -25, -23 }, /* Jog frame 2 @ 45deg */
    { 1042, 145, 20, 2, -20, -15 }, /* Jog frame 2 @ 90deg */
    { 1062, 147, 23, 4, -24, -25 }, /* Jog frame 2 @ 135deg */
    { 1085, 151, 27, 4, -27, -25 }, /* Jog frame 3 @ 45deg */
    { 1112, 155, 19, 2, -20, -17 }, /* Jog frame 3 @ 90deg */
    { 1131, 157, 26, 4, -25, -27 }, /* Jog frame 3 @ 135deg */
    { 1157, 161, 28, 4, -27, -25 }, /* Jog frame 4 @ 45deg */
    { 1185, 165, 20, 3, -20, -18 }, /* Jog frame 4 @ 90deg */
    { 1205, 168, 28, 4, -25, -27 }, /* Jog frame 4 @ 135deg */
    { 1233, 172, 23, 4, -27, -26 }, /* Jog frame 5 @ 45deg */
    { 1256, 176, 19, 2, -20, -18 }, /* Jog frame 5 @ 90deg */
    { 1275, 178, 32, 4, -25, -27 }, /* Jog frame 5 @ 135deg */
    { 1307, 182, 24, 3, -25, -23 }, /* Jog frame 6 @ 45deg */
    { 1331, 185, 20, 2, -20, -14 }, /* Jog frame 6 @ 90deg */
    { 1351, 187, 21, 4, -25, -25 }, /* Jog frame 6 @ 135deg */
    { 1372, 191, 30, 3, -25, -23 }, /* Jog frame 7 @ 45deg */
    { 1402, 194, 19, 2, -20, -14 }, /* Jog frame 7 @ 90deg */
    { 1421, 196, 25, 4, -25, -25 }, /* Jog frame 7 @ 135deg */
    { 1446, 200, 23, 4, -27, -25 }, /* Jog frame 8 @ 45deg */
    { 1469, 204, 20, 2, -20, -17 }, /* Jog frame 8 @ 90deg */
    { 1489, 206, 26, 4, -25, -27 }, /* Jog frame 8 @ 135deg */
    { 1515, 210, 27, 4, -27, -26 }, /* Jog frame 9 @ 45deg */
    { 1542, 214, 19, 2, -20, -18 }, /* Jog frame 9 @ 90deg */
    { 1561, 216, 24, 4, -25, -27 }, /* Jog frame 9 @ 135deg */
    { 1585, 220, 26, 4, -27, -22 }, /* Run frame 0 @ 45deg */
    { 1611, 224, 21, 3, -20, -17 }, /* Run frame 0 @ 90deg */
    { 1632, 227, 23, 4, -27, -27 }, /* Run frame 0 @ 135deg */
    { 1655, 231, 27, 4, -26, -25 }, /* Run frame 1 @ 45deg */
    { 1682, 235, 19, 2, -20, -16 }, /* Run frame 1 @ 90deg */
    { 1701, 237, 25, 4, -25, -26 }, /* Run frame 1 @ 135deg */
    { 1726, 241, 25, 4, -26, -25 }, /* Run frame 2 @ 45deg */
    { 1751, 245, 19, 2, -20, -16 }, /* Run frame 2 @ 90deg */
    { 1770, 247, 25, 4, -25, -26 }, /* Run frame 2 @ 135deg */
    { 1795, 251, 27, 4, -26, -25 }, /* Run frame 3 @ 45deg */
    { 1822, 255, 19, 2, -20, -16 }, /* Run frame 3 @ 90deg */
    { 1841, 257, 25, 4, -25, -26 }, /* Run frame 3 @ 135deg */
    { 1866, 261, 27, 4, -25, -23 }, /* Run frame 4 @ 45deg */
    { 1893, 265, 20, 2, -20, -14 }, /* Run frame 4 @ 90deg */
    { 1913, 267, 25, 4, -25, -25 }, /* Run frame 4 @ 135deg */
    { 1938, 271, 27, 4, -25, -24 }, /* Run frame 5 @ 45deg */
    { 1965, 275, 20, 2, -20, -15 }, /* Run frame 5 @ 90deg */
    { 1985, 277, 25, 4, -25, -25 }, /* Run frame 5 @ 135deg */
    { 2010, 281, 27, 4, -26, -25 }, /* Run frame 6 @ 45deg */
    { 2037, 285, 19, 2, -20, -16 }, /* Run frame 6 @ 90deg */
    { 2056, 287, 25, 4, -25, -26 }, /* Run frame 6 @ 135deg */
    { 2081, 291, 27, 4, -26, -25 }, /* Run frame 7 @ 45deg */
    { 2108, 295, 19, 2, -20, -16 }, /* Run frame 7 @ 90deg */
    { 2127, 297, 25, 4, -25, -26 }, /* Run frame 7 @ 135deg */
    { 2152, 301, 27, 4, -25, -24 }, /* Run frame 8 @ 45deg */
    { 2179, 305, 20, 2, -20, -15 }, /* Run frame 8 @ 90deg */
    { 2199, 307, 25, 4, -25, -25 }, /* Run frame 8 @ 135deg */
    { 2224, 311, 26, 4, -27, -22 }, /* Dash frame 0 @ 45deg */
    { 2250, 315, 21, 3, -20, -17 }, /* Dash frame 0 @ 90deg */
    { 2271, 318, 23, 4, -27, -27 }, /* Dash frame 0 @ 135deg */
    { 2294, 322, 30, 4, -27, -22 }, /* Dash frame 1 @ 45deg */
    { 2324, 326, 19, 2, -20, -18 }, /* Dash frame 1 @ 90deg */
    { 2343, 328, 27, 4, -28, -27 }, /* Dash frame 1 @ 135deg */
    { 2370, 332, 30, 4, -27, -22 }, /* Dash frame 2 @ 45deg */
    { 2400, 336, 21, 3, -20, -18 }, /* Dash frame 2 @ 90deg */
    { 2421, 339, 28, 4, -28, -27 }, /* Dash frame 2 @ 135deg */
    { 2449, 343, 30, 4, -27, -22 }, /* Dash frame 3 @ 45deg */
    { 2479, 347, 19, 2, -20, -18 }, /* Dash frame 3 @ 90deg */
    { 2498, 349, 25, 4, -28, -27 }, /* Dash frame 3 @ 135deg */
    { 2523, 353, 30, 4, -27, -22 }, /* Dash frame 4 @ 45deg */
    { 2553, 357, 21, 3, -20, -18 }, /* Dash frame 4 @ 90deg */
    { 2574, 360, 28, 4, -28, -27 }, /* Dash frame 4 @ 135deg */
    { 2602, 364, 24, 3, -26, -22 }, /* Air Walk frame 0 @ 45deg */
    { 2626, 367, 22, 2, -23, -13 }, /* Air Walk frame 0 @ 90deg */
    { 2648, 369, 24, 4, -25, -26 }, /* Air Walk frame 0 @ 135deg */
    { 2672, 373, 27, 3, -26, -22 }, /* Air Walk frame 1 @ 45deg */
    { 2699, 376, 18, 2, -23, -13 }, /* Air Walk frame 1 @ 90deg */
    { 2717, 378, 24, 4, -25, -26 }, /* Air Walk frame 1 @ 135deg */
    { 2741, 382, 30, 4, -29, -26 }, /* Air Walk frame 2 @ 45deg */
    { 2771, 386, 26, 3, -23, -18 }, /* Air Walk frame 2 @ 90deg */
    { 2797, 389, 30, 4, -29, -29 }, /* Air Walk frame 2 @ 135deg */
    { 2827, 393, 24, 4, -30, -27 }, /* Air Walk frame 3 @ 45deg */
    { 2851, 397, 24, 3, -23, -19 }, /* Air Walk frame 3 @ 90deg */
    { 2875, 400, 28, 4, -29, -30 }, /* Air Walk frame 3 @ 135deg */
    { 2903, 404, 26, 4, -29, -26 }, /* Air Walk frame 4 @ 45deg */
    { 2929, 408, 25, 3, -23, -18 }, /* Air Walk frame 4 @ 90deg */
    { 2954, 411, 28, 4, -27, -29 }, /* Air Walk frame 4 @ 135deg */
    { 2982, 415, 26, 3, -29, -26 }, /* Air Walk frame 5 @ 45deg */
    { 3008, 418, 24, 2, -23, -18 }, /* Air Walk frame 5 @ 90deg */
    { 3032, 420, 27, 4, -25, -29 }, /* Air Walk frame 5 @ 135deg */
    { 3059, 424, 27, 3, -26, -22 }, /* Air Walk frame 6 @ 45deg */
    { 3086, 427, 22, 2, -23, -13 }, /* Air Walk frame 6 @ 90deg */
    { 3108, 429, 24, 4, -25, -26 }, /* Air Walk frame 6 @ 135deg */
    { 3132, 433, 32, 3, -27, -23 }, /* Air Walk frame 7 @ 45deg */
    { 3164, 436, 24, 2, -23, -14 }, /* Air Walk frame 7 @ 90deg */
    { 3188, 438, 28, 4, -25, -27 }, /* Air Walk frame 7 @ 135deg */
    { 3216, 442, 26, 4, -29, -26 }, /* Air Walk frame 8 @ 45deg */
    { 3242, 446, 25, 3, -23, -18 }, /* Air Walk frame 8 @ 90deg */
    { 3267, 449, 30, 4, -29, -29 }, /* Air Walk frame 8 @ 135deg */
    { 3297, 453, 24, 4, -29, -26 }, /* Air Walk frame 9 @ 45deg */
    { 3321, 457, 26, 3, -23, -18 }, /* Air Walk frame 9 @ 90deg */
    { 3347, 460, 32, 4, -30, -29 }, /* Air Walk frame 9 @ 135deg */
    { 3379, 464, 30, 4, -27, -24 }, /* Air Walk frame 10 @ 45deg */
    { 3409, 468, 26, 3, -23, -15 }, /* Air Walk frame 10 @ 90deg */
    { 3435, 471, 33, 4, -30, -27 }, /* Air Walk frame 10 @ 135deg */
    { 3468, 475, 24, 3, -27, -23 }, /* Air Walk frame 11 @ 45deg */
    { 3492, 478, 24, 2, -23, -14 }, /* Air Walk frame 11 @ 90deg */
    { 3516, 480, 28, 4, -30, -27 }, /* Air Walk frame 11 @ 135deg */
};
