/* Generated by tools/convert_sonic.py. Do not edit by hand. */

#include "sonic_data.h"

const SonicPiece sonic_pieces[] = {
    { 0, 0, 15, 0 }, /* Idle frame 0 piece 0 */
    { 8, 32, 8, 16 }, /* Idle frame 0 piece 1 */
    { 0, 0, 15, 0 }, /* Walk frame 0 piece 0 */
    { 8, 32, 4, 16 }, /* Walk frame 0 piece 1 */
    { 0, 0, 11, 0 }, /* Walk frame 1 piece 0 */
    { 0, 32, 8, 12 }, /* Walk frame 1 piece 1 */
    { 0, 0, 15, 0 }, /* Walk frame 2 piece 0 */
    { 0, 32, 12, 16 }, /* Walk frame 2 piece 1 */
    { 32, 24, 0, 20 }, /* Walk frame 2 piece 2 */
    { 0, 0, 15, 0 }, /* Walk frame 3 piece 0 */
    { 0, 32, 12, 16 }, /* Walk frame 3 piece 1 */
    { 32, 24, 0, 20 }, /* Walk frame 3 piece 2 */
    { 0, 0, 15, 0 }, /* Walk frame 4 piece 0 */
    { 0, 32, 12, 16 }, /* Walk frame 4 piece 1 */
    { 32, 24, 0, 20 }, /* Walk frame 4 piece 2 */
    { 0, 0, 15, 0 }, /* Walk frame 5 piece 0 */
    { 0, 32, 12, 16 }, /* Walk frame 5 piece 1 */
    { 0, 0, 15, 0 }, /* Walk frame 6 piece 0 */
    { 0, 32, 4, 16 }, /* Walk frame 6 piece 1 */
    { 0, 0, 15, 0 }, /* Walk frame 7 piece 0 */
    { 0, 32, 12, 16 }, /* Walk frame 7 piece 1 */
    { 0, 0, 15, 0 }, /* Walk frame 8 piece 0 */
    { 0, 32, 12, 16 }, /* Walk frame 8 piece 1 */
    { 32, 24, 0, 20 }, /* Walk frame 8 piece 2 */
    { 0, 0, 15, 0 }, /* Walk frame 9 piece 0 */
    { 0, 32, 12, 16 }, /* Walk frame 9 piece 1 */
    { 32, 16, 1, 20 }, /* Walk frame 9 piece 2 */
    { 0, 0, 15, 0 }, /* Walk frame 10 piece 0 */
    { 0, 32, 12, 16 }, /* Walk frame 10 piece 1 */
    { 32, 24, 0, 20 }, /* Walk frame 10 piece 2 */
    { 0, 0, 15, 0 }, /* Walk frame 11 piece 0 */
    { 0, 32, 12, 16 }, /* Walk frame 11 piece 1 */
    { 0, 0, 15, 0 }, /* Jog frame 0 piece 0 */
    { 0, 32, 12, 16 }, /* Jog frame 0 piece 1 */
    { 32, 16, 0, 20 }, /* Jog frame 0 piece 2 */
    { 0, 0, 15, 0 }, /* Jog frame 1 piece 0 */
    { 8, 32, 8, 16 }, /* Jog frame 1 piece 1 */
    { 0, 0, 15, 0 }, /* Jog frame 2 piece 0 */
    { 0, 32, 8, 16 }, /* Jog frame 2 piece 1 */
    { 0, 0, 15, 0 }, /* Jog frame 3 piece 0 */
    { 0, 32, 4, 16 }, /* Jog frame 3 piece 1 */
    { 0, 0, 15, 0 }, /* Jog frame 4 piece 0 */
    { 0, 32, 12, 16 }, /* Jog frame 4 piece 1 */
    { 32, 24, 0, 20 }, /* Jog frame 4 piece 2 */
    { 0, 0, 15, 0 }, /* Jog frame 5 piece 0 */
    { 0, 32, 12, 16 }, /* Jog frame 5 piece 1 */
    { 0, 0, 15, 0 }, /* Jog frame 6 piece 0 */
    { 8, 32, 8, 16 }, /* Jog frame 6 piece 1 */
    { 0, 0, 15, 0 }, /* Jog frame 7 piece 0 */
    { 0, 32, 8, 16 }, /* Jog frame 7 piece 1 */
    { 0, 0, 15, 0 }, /* Jog frame 8 piece 0 */
    { 0, 32, 4, 16 }, /* Jog frame 8 piece 1 */
    { 0, 0, 15, 0 }, /* Jog frame 9 piece 0 */
    { 0, 32, 12, 16 }, /* Jog frame 9 piece 1 */
    { 0, 0, 15, 0 }, /* Run frame 0 piece 0 */
    { 0, 32, 8, 16 }, /* Run frame 0 piece 1 */
    { 32, 0, 1, 19 }, /* Run frame 0 piece 2 */
    { 0, 0, 15, 0 }, /* Run frame 1 piece 0 */
    { 0, 32, 12, 16 }, /* Run frame 1 piece 1 */
    { 0, 0, 15, 0 }, /* Run frame 2 piece 0 */
    { 0, 32, 12, 16 }, /* Run frame 2 piece 1 */
    { 0, 0, 15, 0 }, /* Run frame 3 piece 0 */
    { 0, 32, 12, 16 }, /* Run frame 3 piece 1 */
    { 0, 0, 15, 0 }, /* Run frame 4 piece 0 */
    { 0, 32, 12, 16 }, /* Run frame 4 piece 1 */
    { 0, 0, 15, 0 }, /* Run frame 5 piece 0 */
    { 0, 32, 12, 16 }, /* Run frame 5 piece 1 */
    { 0, 0, 15, 0 }, /* Run frame 6 piece 0 */
    { 0, 32, 12, 16 }, /* Run frame 6 piece 1 */
    { 0, 0, 15, 0 }, /* Run frame 7 piece 0 */
    { 0, 32, 12, 16 }, /* Run frame 7 piece 1 */
    { 0, 0, 15, 0 }, /* Run frame 8 piece 0 */
    { 0, 32, 12, 16 }, /* Run frame 8 piece 1 */
    { 0, 0, 15, 0 }, /* Dash frame 0 piece 0 */
    { 0, 32, 8, 16 }, /* Dash frame 0 piece 1 */
    { 32, 0, 1, 19 }, /* Dash frame 0 piece 2 */
    { 0, 0, 15, 0 }, /* Dash frame 1 piece 0 */
    { 8, 32, 8, 16 }, /* Dash frame 1 piece 1 */
    { 32, 0, 2, 19 }, /* Dash frame 1 piece 2 */
    { 0, 0, 15, 0 }, /* Dash frame 2 piece 0 */
    { 16, 32, 0, 16 }, /* Dash frame 2 piece 1 */
    { 32, 0, 2, 17 }, /* Dash frame 2 piece 2 */
    { 0, 0, 15, 0 }, /* Dash frame 3 piece 0 */
    { 8, 32, 4, 16 }, /* Dash frame 3 piece 1 */
    { 32, 0, 2, 18 }, /* Dash frame 3 piece 2 */
    { 0, 0, 15, 0 }, /* Dash frame 4 piece 0 */
    { 16, 32, 0, 16 }, /* Dash frame 4 piece 1 */
    { 32, 0, 2, 17 }, /* Dash frame 4 piece 2 */
    { 0, 0, 15, 0 }, /* Skid frame 0 piece 0 */
    { 0, 32, 4, 16 }, /* Skid frame 0 piece 1 */
    { 0, 0, 15, 0 }, /* Skid frame 1 piece 0 */
    { 8, 32, 4, 16 }, /* Skid frame 1 piece 1 */
    { 0, 0, 15, 0 }, /* Skid frame 2 piece 0 */
    { 8, 32, 8, 16 }, /* Skid frame 2 piece 1 */
    { 0, 0, 15, 0 }, /* Skid frame 3 piece 0 */
    { 16, 32, 4, 16 }, /* Skid frame 3 piece 1 */
    { 32, 16, 1, 18 }, /* Skid frame 3 piece 2 */
    { 0, 0, 15, 0 }, /* Skid frame 4 piece 0 */
    { 16, 32, 4, 16 }, /* Skid frame 4 piece 1 */
    { 32, 16, 1, 18 }, /* Skid frame 4 piece 2 */
    { 0, 0, 15, 0 }, /* Skid frame 5 piece 0 */
    { 24, 32, 0, 16 }, /* Skid frame 5 piece 1 */
    { 32, 8, 2, 17 }, /* Skid frame 5 piece 2 */
    { 32, 32, 0, 20 }, /* Skid frame 5 piece 3 */
    { 0, 0, 15, 0 }, /* Skid frame 6 piece 0 */
    { 16, 32, 4, 16 }, /* Skid frame 6 piece 1 */
    { 0, 0, 15, 0 }, /* Skid frame 7 piece 0 */
    { 16, 32, 4, 16 }, /* Skid frame 7 piece 1 */
    { 0, 0, 15, 0 }, /* Skid frame 8 piece 0 */
    { 24, 32, 0, 16 }, /* Skid frame 8 piece 1 */
    { 32, 8, 2, 17 }, /* Skid frame 8 piece 2 */
    { 0, 0, 15, 0 }, /* Skid frame 9 piece 0 */
    { 24, 32, 0, 16 }, /* Skid frame 9 piece 1 */
    { 32, 8, 2, 17 }, /* Skid frame 9 piece 2 */
    { 32, 32, 0, 20 }, /* Skid frame 9 piece 3 */
    { 0, 0, 15, 0 }, /* Skid frame 10 piece 0 */
    { 16, 32, 4, 16 }, /* Skid frame 10 piece 1 */
    { 0, 0, 15, 0 }, /* Skid frame 11 piece 0 */
    { 16, 32, 4, 16 }, /* Skid frame 11 piece 1 */
    { 0, 0, 15, 0 }, /* Skid frame 12 piece 0 */
    { 24, 32, 0, 16 }, /* Skid frame 12 piece 1 */
    { 32, 8, 2, 17 }, /* Skid frame 12 piece 2 */
    { 0, 0, 15, 0 }, /* Skid Turn frame 0 piece 0 */
    { 24, 32, 0, 16 }, /* Skid Turn frame 0 piece 1 */
    { 32, 16, 1, 17 }, /* Skid Turn frame 0 piece 2 */
    { 32, 32, 0, 19 }, /* Skid Turn frame 0 piece 3 */
    { 0, 0, 15, 0 }, /* Skid Turn frame 1 piece 0 */
    { 16, 32, 4, 16 }, /* Skid Turn frame 1 piece 1 */
    { 32, 8, 2, 18 }, /* Skid Turn frame 1 piece 2 */
    { 32, 32, 0, 21 }, /* Skid Turn frame 1 piece 3 */
    { 0, 0, 15, 0 }, /* Skid Turn frame 2 piece 0 */
    { 8, 32, 4, 16 }, /* Skid Turn frame 2 piece 1 */
    { 0, 0, 15, 0 }, /* Skid Turn frame 3 piece 0 */
    { 8, 32, 4, 16 }, /* Skid Turn frame 3 piece 1 */
    { 0, 0, 15, 0 }, /* Air Walk frame 0 piece 0 */
    { 8, 32, 5, 16 }, /* Air Walk frame 0 piece 1 */
    { 0, 0, 11, 0 }, /* Air Walk frame 1 piece 0 */
    { 0, 32, 5, 12 }, /* Air Walk frame 1 piece 1 */
    { 0, 0, 15, 0 }, /* Air Walk frame 2 piece 0 */
    { 0, 32, 12, 16 }, /* Air Walk frame 2 piece 1 */
    { 32, 16, 1, 20 }, /* Air Walk frame 2 piece 2 */
    { 0, 0, 15, 0 }, /* Air Walk frame 3 piece 0 */
    { 0, 32, 12, 16 }, /* Air Walk frame 3 piece 1 */
    { 32, 16, 1, 20 }, /* Air Walk frame 3 piece 2 */
    { 0, 0, 15, 0 }, /* Air Walk frame 4 piece 0 */
    { 0, 32, 12, 16 }, /* Air Walk frame 4 piece 1 */
    { 32, 24, 0, 20 }, /* Air Walk frame 4 piece 2 */
    { 0, 0, 15, 0 }, /* Air Walk frame 5 piece 0 */
    { 8, 32, 8, 16 }, /* Air Walk frame 5 piece 1 */
    { 0, 0, 15, 0 }, /* Air Walk frame 6 piece 0 */
    { 0, 32, 5, 16 }, /* Air Walk frame 6 piece 1 */
    { 0, 0, 15, 0 }, /* Air Walk frame 7 piece 0 */
    { 0, 32, 13, 16 }, /* Air Walk frame 7 piece 1 */
    { 0, 0, 15, 0 }, /* Air Walk frame 8 piece 0 */
    { 0, 32, 0, 16 }, /* Air Walk frame 8 piece 1 */
    { 32, 24, 0, 17 }, /* Air Walk frame 8 piece 2 */
    { 0, 0, 15, 0 }, /* Air Walk frame 9 piece 0 */
    { 0, 32, 12, 16 }, /* Air Walk frame 9 piece 1 */
    { 32, 16, 1, 20 }, /* Air Walk frame 9 piece 2 */
    { 0, 0, 15, 0 }, /* Air Walk frame 10 piece 0 */
    { 0, 32, 12, 16 }, /* Air Walk frame 10 piece 1 */
    { 32, 16, 1, 20 }, /* Air Walk frame 10 piece 2 */
    { 0, 0, 15, 0 }, /* Air Walk frame 11 piece 0 */
    { 0, 32, 12, 16 }, /* Air Walk frame 11 piece 1 */
    { 0, 0, 15, 0 }, /* Jump frame 0 piece 0 */
    { 0, 0, 15, 0 }, /* Jump frame 1 piece 0 */
    { 0, 0, 15, 0 }, /* Jump frame 2 piece 0 */
    { 0, 0, 15, 0 }, /* Jump frame 3 piece 0 */
    { 0, 0, 15, 0 }, /* Jump frame 4 piece 0 */
    { 0, 0, 15, 0 }, /* Jump frame 5 piece 0 */
    { 0, 0, 15, 0 }, /* Jump frame 6 piece 0 */
    { 0, 0, 15, 0 }, /* Jump frame 7 piece 0 */
    { 0, 0, 15, 0 }, /* Jump frame 8 piece 0 */
    { 0, 0, 15, 0 }, /* Jump frame 9 piece 0 */
    { 0, 0, 15, 0 }, /* Jump frame 10 piece 0 */
    { 0, 0, 15, 0 }, /* Jump frame 11 piece 0 */
    { 0, 0, 15, 0 }, /* Jump frame 12 piece 0 */
    { 0, 0, 15, 0 }, /* Jump frame 13 piece 0 */
    { 0, 0, 15, 0 }, /* Jump frame 14 piece 0 */
    { 0, 0, 15, 0 }, /* Jump frame 15 piece 0 */
    { 0, 0, 15, 0 }, /* Push frame 0 piece 0 */
    { 0, 32, 12, 16 }, /* Push frame 0 piece 1 */
    { 0, 0, 15, 0 }, /* Push frame 1 piece 0 */
    { 0, 32, 8, 16 }, /* Push frame 1 piece 1 */
    { 0, 0, 15, 0 }, /* Push frame 2 piece 0 */
    { 0, 32, 8, 16 }, /* Push frame 2 piece 1 */
    { 0, 0, 11, 0 }, /* Push frame 3 piece 0 */
    { 0, 32, 4, 12 }, /* Push frame 3 piece 1 */
    { 0, 0, 15, 0 }, /* Push frame 4 piece 0 */
    { 0, 32, 8, 16 }, /* Push frame 4 piece 1 */
    { 0, 0, 15, 0 }, /* Push frame 5 piece 0 */
    { 0, 32, 8, 16 }, /* Push frame 5 piece 1 */
    { 0, 0, 15, 0 }, /* Push frame 6 piece 0 */
    { 0, 32, 8, 16 }, /* Push frame 6 piece 1 */
    { 0, 0, 15, 0 }, /* Push frame 7 piece 0 */
    { 0, 32, 8, 16 }, /* Push frame 7 piece 1 */
    { 0, 0, 11, 0 }, /* Push frame 8 piece 0 */
    { 0, 32, 4, 12 }, /* Push frame 8 piece 1 */
    { 0, 0, 15, 0 }, /* Push frame 9 piece 0 */
    { 0, 32, 12, 16 }, /* Push frame 9 piece 1 */
    { 0, 0, 15, 0 }, /* Look Up frame 0 piece 0 */
    { 8, 32, 8, 16 }, /* Look Up frame 0 piece 1 */
    { 0, 0, 15, 0 }, /* Look Up frame 1 piece 0 */
    { 8, 32, 9, 16 }, /* Look Up frame 1 piece 1 */
    { 0, 0, 15, 0 }, /* Look Up frame 2 piece 0 */
    { 8, 32, 9, 16 }, /* Look Up frame 2 piece 1 */
    { 0, 0, 15, 0 }, /* Look Up frame 3 piece 0 */
    { 8, 32, 9, 16 }, /* Look Up frame 3 piece 1 */
    { 0, 0, 15, 0 }, /* Look Up frame 4 piece 0 */
    { 8, 32, 9, 16 }, /* Look Up frame 4 piece 1 */
    { 0, 0, 15, 0 }, /* Look Up frame 5 piece 0 */
    { 8, 32, 9, 16 }, /* Look Up frame 5 piece 1 */
    { 0, 0, 15, 0 }, /* Look Up frame 6 piece 0 */
    { 8, 32, 9, 16 }, /* Look Up frame 6 piece 1 */
    { 0, 0, 15, 0 }, /* Look Up frame 7 piece 0 */
    { 8, 32, 9, 16 }, /* Look Up frame 7 piece 1 */
    { 0, 0, 15, 0 }, /* Crouch frame 0 piece 0 */
    { 8, 32, 8, 16 }, /* Crouch frame 0 piece 1 */
    { 0, 0, 11, 0 }, /* Crouch frame 1 piece 0 */
    { 0, 32, 8, 12 }, /* Crouch frame 1 piece 1 */
    { 0, 0, 11, 0 }, /* Crouch frame 2 piece 0 */
    { 0, 0, 15, 0 }, /* Crouch frame 3 piece 0 */
    { 0, 0, 15, 0 }, /* Crouch frame 4 piece 0 */
    { 0, 0, 11, 0 }, /* Crouch frame 5 piece 0 */
    { 0, 32, 8, 12 }, /* Crouch frame 5 piece 1 */
    { 0, 0, 11, 0 }, /* Spring Twirl frame 0 piece 0 */
    { 0, 32, 9, 12 }, /* Spring Twirl frame 0 piece 1 */
    { 0, 0, 11, 0 }, /* Spring Twirl frame 1 piece 0 */
    { 0, 32, 9, 12 }, /* Spring Twirl frame 1 piece 1 */
    { 0, 0, 15, 0 }, /* Spring Twirl frame 2 piece 0 */
    { 0, 32, 9, 16 }, /* Spring Twirl frame 2 piece 1 */
    { 0, 0, 11, 0 }, /* Spring Twirl frame 3 piece 0 */
    { 0, 32, 5, 12 }, /* Spring Twirl frame 3 piece 1 */
    { 0, 0, 11, 0 }, /* Spring Twirl frame 4 piece 0 */
    { 0, 32, 5, 12 }, /* Spring Twirl frame 4 piece 1 */
    { 0, 0, 11, 0 }, /* Spring Twirl frame 5 piece 0 */
    { 0, 32, 5, 12 }, /* Spring Twirl frame 5 piece 1 */
    { 0, 0, 15, 0 }, /* Spring Twirl frame 6 piece 0 */
    { 0, 32, 9, 16 }, /* Spring Twirl frame 6 piece 1 */
    { 0, 0, 15, 0 }, /* Spring Twirl frame 7 piece 0 */
    { 0, 32, 9, 16 }, /* Spring Twirl frame 7 piece 1 */
    { 0, 0, 15, 0 }, /* Spring Twirl frame 8 piece 0 */
    { 0, 32, 9, 16 }, /* Spring Twirl frame 8 piece 1 */
    { 0, 0, 11, 0 }, /* Spring Twirl frame 9 piece 0 */
    { 0, 32, 9, 12 }, /* Spring Twirl frame 9 piece 1 */
    { 0, 0, 11, 0 }, /* Spring Diagonal frame 0 piece 0 */
    { 0, 32, 5, 12 }, /* Spring Diagonal frame 0 piece 1 */
    { 0, 0, 11, 0 }, /* Spring Diagonal frame 1 piece 0 */
    { 0, 32, 5, 12 }, /* Spring Diagonal frame 1 piece 1 */
    { 0, 0, 15, 0 }, /* Hurt frame 0 piece 0 */
    { 0, 0, 15, 0 }, /* Hurt frame 1 piece 0 */
    { 32, 8, 1, 16 }, /* Hurt frame 1 piece 1 */
    { 0, 0, 15, 0 }, /* Hurt frame 2 piece 0 */
    { 32, 0, 3, 16 }, /* Hurt frame 2 piece 1 */
    { 0, 0, 15, 0 }, /* Hurt frame 3 piece 0 */
    { 32, 0, 2, 16 }, /* Hurt frame 3 piece 1 */
    { 0, 0, 15, 0 }, /* Hurt frame 4 piece 0 */
    { 32, 0, 3, 16 }, /* Hurt frame 4 piece 1 */
    { 0, 0, 15, 0 }, /* Die frame 0 piece 0 */
    { 0, 32, 13, 16 }, /* Die frame 0 piece 1 */
    { 32, 0, 1, 24 }, /* Die frame 0 piece 2 */
    { 32, 40, 0, 26 }, /* Die frame 0 piece 3 */
};

const SonicFrame sonic_frames[] = {
    { 0, 0, 19, 2, -16, -20, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Idle frame 0 */
    { 19, 2, 18, 2, -13, -20, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Walk frame 0 */
    { 37, 4, 15, 2, -13, -20, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Walk frame 1 */
    { 52, 6, 21, 3, -18, -20, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Walk frame 2 */
    { 73, 9, 21, 3, -19, -20, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Walk frame 3 */
    { 94, 12, 21, 3, -18, -20, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Walk frame 4 */
    { 115, 15, 20, 2, -18, -20, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Walk frame 5 */
    { 135, 17, 18, 2, -13, -20, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Walk frame 6 */
    { 153, 19, 20, 2, -14, -20, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Walk frame 7 */
    { 173, 21, 21, 3, -17, -20, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Walk frame 8 */
    { 194, 24, 22, 3, -18, -20, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Walk frame 9 */
    { 216, 27, 21, 3, -15, -20, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Walk frame 10 */
    { 237, 30, 20, 2, -14, -20, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Walk frame 11 */
    { 257, 32, 21, 3, -19, -17, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Jog frame 0 */
    { 278, 35, 19, 2, -18, -17, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Jog frame 1 */
    { 297, 37, 19, 2, -15, -17, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Jog frame 2 */
    { 316, 39, 18, 2, -17, -17, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Jog frame 3 */
    { 334, 41, 21, 3, -18, -17, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Jog frame 4 */
    { 355, 44, 20, 2, -18, -18, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Jog frame 5 */
    { 375, 46, 19, 2, -14, -18, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Jog frame 6 */
    { 394, 48, 19, 2, -14, -18, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Jog frame 7 */
    { 413, 50, 18, 2, -17, -18, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Jog frame 8 */
    { 431, 52, 20, 2, -18, -18, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Jog frame 9 */
    { 451, 54, 21, 3, -17, -14, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Run frame 0 */
    { 472, 57, 20, 2, -16, -18, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Run frame 1 */
    { 492, 59, 20, 2, -16, -18, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Run frame 2 */
    { 512, 61, 20, 2, -16, -18, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Run frame 3 */
    { 532, 63, 20, 2, -14, -18, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Run frame 4 */
    { 552, 65, 20, 2, -15, -18, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Run frame 5 */
    { 572, 67, 20, 2, -16, -18, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Run frame 6 */
    { 592, 69, 20, 2, -16, -18, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Run frame 7 */
    { 612, 71, 20, 2, -15, -18, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Run frame 8 */
    { 632, 73, 21, 3, -17, -14, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Dash frame 0 */
    { 653, 76, 22, 3, -18, -13, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Dash frame 1 */
    { 675, 79, 20, 3, -18, -13, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Dash frame 2 */
    { 695, 82, 21, 3, -18, -13, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Dash frame 3 */
    { 716, 85, 20, 3, -18, -13, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Dash frame 4 */
    { 736, 88, 18, 2, -13, -17, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Skid frame 0 */
    { 754, 90, 18, 2, -14, -17, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Skid frame 1 */
    { 772, 92, 19, 2, -14, -17, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Skid frame 2 */
    { 791, 94, 20, 3, -16, -17, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Skid frame 3 */
    { 811, 97, 20, 3, -18, -17, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Skid frame 4 */
    { 831, 100, 21, 4, -19, -17, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Skid frame 5 */
    { 852, 104, 18, 2, -16, -17, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Skid frame 6 */
    { 870, 106, 18, 2, -15, -17, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Skid frame 7 */
    { 888, 108, 20, 3, -18, -17, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Skid frame 8 */
    { 908, 111, 21, 4, -19, -17, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Skid frame 9 */
    { 929, 115, 18, 2, -16, -17, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Skid frame 10 */
    { 947, 117, 18, 2, -15, -17, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Skid frame 11 */
    { 965, 119, 20, 3, -18, -17, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Skid frame 12 */
    { 985, 122, 20, 4, -18, -17, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Skid Turn frame 0 */
    { 1005, 126, 22, 4, -16, -17, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Skid Turn frame 1 */
    { 1027, 130, 18, 2, -12, -17, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Skid Turn frame 2 */
    { 1045, 132, 18, 2, -12, -17, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Skid Turn frame 3 */
    { 1063, 134, 20, 2, -13, -18, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Air Walk frame 0 */
    { 1083, 136, 16, 2, -13, -18, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Air Walk frame 1 */
    { 1099, 138, 22, 3, -18, -18, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Air Walk frame 2 */
    { 1121, 141, 22, 3, -19, -18, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Air Walk frame 3 */
    { 1143, 144, 21, 3, -18, -18, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Air Walk frame 4 */
    { 1164, 147, 19, 2, -18, -18, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Air Walk frame 5 */
    { 1183, 149, 20, 2, -13, -18, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Air Walk frame 6 */
    { 1203, 151, 24, 2, -14, -18, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Air Walk frame 7 */
    { 1227, 153, 18, 3, -18, -18, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Air Walk frame 8 */
    { 1245, 156, 22, 3, -18, -18, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Air Walk frame 9 */
    { 1267, 159, 22, 3, -15, -18, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Air Walk frame 10 */
    { 1289, 162, 20, 2, -14, -18, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Air Walk frame 11 */
    { 1309, 164, 16, 1, -16, -16, 120, -10, -15, 10, 15, -7, -15, 7, 15 }, /* Jump frame 0 */
    { 1325, 165, 16, 1, -16, -16, 120, -10, -15, 10, 15, -7, -15, 7, 15 }, /* Jump frame 1 */
    { 1341, 166, 16, 1, -16, -16, 120, -10, -15, 10, 15, -7, -15, 7, 15 }, /* Jump frame 2 */
    { 1357, 167, 16, 1, -16, -16, 120, -10, -15, 10, 15, -7, -15, 7, 15 }, /* Jump frame 3 */
    { 1373, 168, 16, 1, -16, -16, 120, -10, -15, 10, 15, -7, -15, 7, 15 }, /* Jump frame 4 */
    { 1389, 169, 16, 1, -16, -16, 120, -10, -15, 10, 15, -7, -15, 7, 15 }, /* Jump frame 5 */
    { 1405, 170, 16, 1, -16, -16, 120, -10, -15, 10, 15, -7, -15, 7, 15 }, /* Jump frame 6 */
    { 1421, 171, 16, 1, -16, -16, 120, -10, -15, 10, 15, -7, -15, 7, 15 }, /* Jump frame 7 */
    { 1437, 172, 16, 1, -16, -16, 120, -10, -15, 10, 15, -7, -15, 7, 15 }, /* Jump frame 8 */
    { 1453, 173, 16, 1, -16, -16, 120, -10, -15, 10, 15, -7, -15, 7, 15 }, /* Jump frame 9 */
    { 1469, 174, 16, 1, -16, -16, 120, -10, -15, 10, 15, -7, -15, 7, 15 }, /* Jump frame 10 */
    { 1485, 175, 16, 1, -16, -16, 120, -10, -15, 10, 15, -7, -15, 7, 15 }, /* Jump frame 11 */
    { 1501, 176, 16, 1, -16, -16, 120, -10, -15, 10, 15, -7, -15, 7, 15 }, /* Jump frame 12 */
    { 1517, 177, 16, 1, -16, -16, 120, -10, -15, 10, 15, -7, -15, 7, 15 }, /* Jump frame 13 */
    { 1533, 178, 16, 1, -16, -16, 120, -10, -15, 10, 15, -7, -15, 7, 15 }, /* Jump frame 14 */
    { 1549, 179, 16, 1, -16, -16, 120, -10, -15, 10, 15, -7, -15, 7, 15 }, /* Jump frame 15 */
    { 1565, 180, 20, 2, -19, -17, 9, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Push frame 0 */
    { 1585, 182, 19, 2, -19, -17, 9, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Push frame 1 */
    { 1604, 184, 19, 2, -18, -17, 6, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Push frame 2 */
    { 1623, 186, 14, 2, -14, -17, 4, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Push frame 3 */
    { 1637, 188, 19, 2, -18, -17, 6, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Push frame 4 */
    { 1656, 190, 19, 2, -18, -17, 9, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Push frame 5 */
    { 1675, 192, 19, 2, -18, -17, 9, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Push frame 6 */
    { 1694, 194, 19, 2, -17, -17, 6, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Push frame 7 */
    { 1713, 196, 14, 2, -14, -17, 4, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Push frame 8 */
    { 1727, 198, 20, 2, -19, -17, 6, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Push frame 9 */
    { 1747, 200, 19, 2, -16, -20, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Look Up frame 0 */
    { 1766, 202, 22, 2, -16, -21, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Look Up frame 1 */
    { 1788, 204, 22, 2, -17, -21, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Look Up frame 2 */
    { 1810, 206, 22, 2, -17, -21, 384, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Look Up frame 3 */
    { 1832, 208, 22, 2, -16, -21, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Look Up frame 4 */
    { 1854, 210, 22, 2, -16, -21, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Look Up frame 5 */
    { 1876, 212, 22, 2, -17, -21, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Look Up frame 6 */
    { 1898, 214, 22, 2, -16, -21, 384, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Look Up frame 7 */
    { 1920, 216, 19, 2, -16, -20, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Crouch frame 0 */
    { 1939, 218, 15, 2, -12, -20, 256, -10, -16, 10, 20, -9, -16, 9, 20 }, /* Crouch frame 1 */
    { 1954, 220, 12, 1, -9, -12, 256, -10, -14, 10, 20, -9, -14, 9, 20 }, /* Crouch frame 2 */
    { 1966, 221, 16, 1, -10, -11, 256, -10, -12, 10, 20, -9, -12, 9, 20 }, /* Crouch frame 3 */
    { 1982, 222, 16, 1, -11, -6, 256, -10, -6, 10, 20, -9, -6, 9, 20 }, /* Crouch frame 4 */
    { 1998, 223, 15, 2, -12, -20, 256, -10, -16, 10, 20, -9, -16, 9, 20 }, /* Crouch frame 5 */
    { 2013, 225, 18, 2, -11, -22, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Spring Twirl frame 0 */
    { 2031, 227, 18, 2, -11, -22, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Spring Twirl frame 1 */
    { 2049, 229, 22, 2, -14, -22, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Spring Twirl frame 2 */
    { 2071, 231, 16, 2, -9, -22, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Spring Twirl frame 3 */
    { 2087, 233, 16, 2, -8, -22, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Spring Twirl frame 4 */
    { 2103, 235, 16, 2, -6, -22, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Spring Twirl frame 5 */
    { 2119, 237, 22, 2, -13, -22, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Spring Twirl frame 6 */
    { 2141, 239, 22, 2, -14, -22, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Spring Twirl frame 7 */
    { 2163, 241, 22, 2, -11, -22, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Spring Twirl frame 8 */
    { 2185, 243, 18, 2, -14, -22, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Spring Twirl frame 9 */
    { 2203, 245, 16, 2, -12, -23, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Spring Diagonal frame 0 */
    { 2219, 247, 16, 2, -12, -23, 256, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Spring Diagonal frame 1 */
    { 2235, 249, 16, 1, -13, -15, 2, -10, -15, 10, 15, -9, -15, 9, 15 }, /* Hurt frame 0 */
    { 2251, 250, 18, 2, -15, -15, 2, -10, -15, 10, 15, -9, -15, 9, 15 }, /* Hurt frame 1 */
    { 2269, 252, 20, 2, -18, -15, 2, -10, -15, 10, 15, -9, -15, 9, 15 }, /* Hurt frame 2 */
    { 2289, 254, 19, 2, -20, -15, 3, -10, -15, 10, 15, -9, -15, 9, 15 }, /* Hurt frame 3 */
    { 2308, 256, 20, 2, -20, -15, 256, -10, -15, 10, 15, -9, -15, 9, 15 }, /* Hurt frame 4 */
    { 2328, 258, 27, 4, -18, -23, 0, -10, -20, 10, 20, -9, -20, 9, 20 }, /* Die frame 0 */
};

const SonicAnim sonic_anims[SONIC_ANIM_COUNT] = {
    { 0, 1, 0, 0 }, /* Idle */
    { 1, 12, 0, 64 }, /* Walk */
    { 13, 10, 0, 96 }, /* Jog */
    { 23, 9, 1, 128 }, /* Run */
    { 32, 5, 1, 256 }, /* Dash */
    { 37, 13, 5, 128 }, /* Skid */
    { 50, 4, 2, 128 }, /* Skid Turn */
    { 54, 12, 0, 64 }, /* Air Walk */
    { 66, 16, 0, 60 }, /* Jump */
    { 82, 10, 0, 1 }, /* Push */
    { 92, 8, 0, 128 }, /* Look Up */
    { 100, 6, 0, 128 }, /* Crouch */
    { 106, 10, 0, 128 }, /* Spring Twirl */
    { 116, 2, 0, 128 }, /* Spring Diagonal */
    { 118, 5, 4, 1 }, /* Hurt */
    { 123, 1, 0, 0 }, /* Die */
};
