/* Generated by tools/convert_objects.py. Do not edit by hand. */

#include "spikelog_data.h"

const ObjPiece spikelog_pieces[] = {
    { 0, 8, 5, 0 },
    { 0, 8, 5, 0 },
};

const ObjFrame spikelog_rotate[2] = {
    { 0, 0, 4, 1, -8, -16, 3 },
    { 4, 1, 4, 1, -8, -16, 3 },
};
