/* Generated by tools/convert_objects.py. Do not edit by hand. */

#include "spikes_data.h"

const ObjPiece spikes_pieces[] = {
    { 0, 0, 15, 0 },
    { 0, 0, 15, 0 },
};

const ObjFrame spikes_v[1] = {
    { 0, 0, 16, 1, -16, -16, 0 },
};

const ObjFrame spikes_h[1] = {
    { 16, 1, 16, 1, -16, -16, 0 },
};
