/* Generated by tools/convert_objects.py. Do not edit by hand. */

#ifndef SPIKES_DATA_H
#define SPIKES_DATA_H

#include <stdint.h>
#include "obj_data.h"

#define SPIKES_PAL 0
#define SPIKES_MAX_FRAME_TILES  16
#define SPIKES_MAX_FRAME_PIECES 1

extern const ObjFrame spikes_v[1];
extern const ObjFrame spikes_h[1];
extern const ObjPiece spikes_pieces[];

#endif
