/* Generated by tools/convert_objects.py. Do not edit by hand. */

#ifndef SPIKELOG_DATA_H
#define SPIKELOG_DATA_H

#include <stdint.h>
#include "obj_data.h"

#define SPIKELOG_PAL 0
#define SPIKELOG_MAX_FRAME_TILES  4
#define SPIKELOG_MAX_FRAME_PIECES 1

extern const ObjFrame spikelog_rotate[2];
extern const ObjPiece spikelog_pieces[];

#endif
