/* Generated by tools/convert_objects.py. Do not edit by hand. */

#ifndef SPRING_DATA_H
#define SPRING_DATA_H

#include <stdint.h>
#include "obj_data.h"   /* ObjFrame/ObjPiece -- shared with signpost_data.h
                          * and every other piece-chunked object's data
                          * header (obj_data.h's own comment). */

#define SPRING_ORIENT_COUNT     3   /* Spring.c's type>>1: 0 V, 1 H, 2 D */
#define SPRING_STREAM_FRAMES    1
#define SPRING_MAX_RESIDENT_TILES  16
#define SPRING_MAX_RESIDENT_PIECES 1
#define SPRING_MAX_STREAM_TILES    22
#define SPRING_MAX_STREAM_PIECES   3

#define SPRING_PAL 0

extern const int8_t spring_hitbox[SPRING_ORIENT_COUNT][4];

extern const ObjFrame spring_resident[SPRING_ORIENT_COUNT];
extern const ObjPiece spring_resident_pieces[];

extern const ObjFrame spring_stream[SPRING_ORIENT_COUNT][SPRING_STREAM_FRAMES];
extern const ObjPiece spring_stream_pieces[];

#endif
