/* Generated by tools/convert_objects.py. Do not edit by hand. */

#include "spring_data.h"

const int8_t spring_hitbox[SPRING_ORIENT_COUNT][4] = {
    { -16, -8, 16, 8 }, /* V */
    { -8, -16, 8, 16 }, /* H */
    { -12, -12, 12, 12 }, /* D */
};

const ObjPiece spring_resident_pieces[] = {
    { 0, 0, 13, 0 },
    { 0, 0, 7, 0 },
    { 0, 0, 15, 0 },
};

const ObjFrame spring_resident[SPRING_ORIENT_COUNT] = {
    { 0, 0, 8, 1, -16, -8, 128 }, /* V */
    { 8, 1, 8, 1, -8, -16, 128 }, /* H */
    { 16, 2, 16, 1, -16, -13, 128 }, /* D */
};

const ObjPiece spring_stream_pieces[] = {
    { 0, 0, 15, 0 },
    { 0, 0, 15, 0 },
    { 0, 0, 15, 0 },
    { 0, 32, 8, 16 },
    { 32, 8, 2, 19 },
};

const ObjFrame spring_stream[SPRING_ORIENT_COUNT][SPRING_STREAM_FRAMES] = {
    { /* V */
        { 0, 0, 16, 1, -16, -24, 512 },
    },
    { /* H */
        { 16, 1, 16, 1, -8, -16, 512 },
    },
    { /* D */
        { 32, 2, 22, 3, -16, -23, 512 },
    },
};
